-- Ethanol Product & Dispatch tables
CREATE TABLE IF NOT EXISTS "EthanolProductEntry" (
    "id" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "yearStart" INTEGER NOT NULL,
    "recADip" DOUBLE PRECISION,
    "recALt" DOUBLE PRECISION,
    "recAStrength" DOUBLE PRECISION,
    "recAVolume" DOUBLE PRECISION,
    "recBDip" DOUBLE PRECISION,
    "recBLt" DOUBLE PRECISION,
    "recBStrength" DOUBLE PRECISION,
    "recBVolume" DOUBLE PRECISION,
    "recCDip" DOUBLE PRECISION,
    "recCLt" DOUBLE PRECISION,
    "recCStrength" DOUBLE PRECISION,
    "recCVolume" DOUBLE PRECISION,
    "issADip" DOUBLE PRECISION,
    "issALt" DOUBLE PRECISION,
    "issAStrength" DOUBLE PRECISION,
    "issAVolume" DOUBLE PRECISION,
    "issBDip" DOUBLE PRECISION,
    "issBLt" DOUBLE PRECISION,
    "issBStrength" DOUBLE PRECISION,
    "issBVolume" DOUBLE PRECISION,
    "issCDip" DOUBLE PRECISION,
    "issCLt" DOUBLE PRECISION,
    "issCStrength" DOUBLE PRECISION,
    "issCVolume" DOUBLE PRECISION,
    "bulkADip" DOUBLE PRECISION,
    "bulkALt" DOUBLE PRECISION,
    "bulkAStrength" DOUBLE PRECISION,
    "bulkAVolume" DOUBLE PRECISION,
    "bulkBDip" DOUBLE PRECISION,
    "bulkBLt" DOUBLE PRECISION,
    "bulkBStrength" DOUBLE PRECISION,
    "bulkBVolume" DOUBLE PRECISION,
    "bulkCDip" DOUBLE PRECISION,
    "bulkCLt" DOUBLE PRECISION,
    "bulkCStrength" DOUBLE PRECISION,
    "bulkCVolume" DOUBLE PRECISION,
    "rsLevel" DOUBLE PRECISION,
    "hfoLevel" DOUBLE PRECISION,
    "lfoLevel" DOUBLE PRECISION,
    "totalStock" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "avgStrength" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "totalDispatch" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "productionBL" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "productionAL" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "remarks" TEXT,
    "userId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "EthanolProductEntry_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "DispatchTruck" (
    "id" TEXT NOT NULL,
    "entryId" TEXT NOT NULL,
    "vehicleNo" TEXT NOT NULL DEFAULT '',
    "partyName" TEXT NOT NULL DEFAULT '',
    "destination" TEXT NOT NULL DEFAULT '',
    "quantityBL" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "strength" DOUBLE PRECISION,
    "remarks" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "DispatchTruck_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "DispatchTruck" ADD CONSTRAINT "DispatchTruck_entryId_fkey"
    FOREIGN KEY ("entryId") REFERENCES "EthanolProductEntry"("id") ON DELETE CASCADE ON UPDATE CASCADE;
