import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  // 1. TDS_PAYABLE account balance and journal lines
  const tdsAcc = await prisma.account.findFirst({ where: { code: '2200' }, select: { id: true, name: true } });
  if (tdsAcc) {
    const lines = await prisma.journalLine.findMany({
      where: { accountId: tdsAcc.id },
      select: { debit: true, credit: true, narration: true, journal: { select: { date: true, refType: true, refId: true, isAutoGenerated: true } } },
      orderBy: { id: 'desc' },
      take: 30,
    });
    console.log('\n=== TDS_PAYABLE (2200) — Recent journal lines ===');
    let bal = 0;
    for (const l of lines) {
      bal += (l.credit || 0) - (l.debit || 0);
      console.log(`${l.journal?.date?.toISOString().slice(0,10)}  Dr ${l.debit||0}  Cr ${l.credit||0}  ${l.narration?.slice(0,70)}  ref=${l.journal?.refType}/${l.journal?.refId||''}  auto=${l.journal?.isAutoGenerated}`);
    }
    const agg = await prisma.journalLine.aggregate({ where: { accountId: tdsAcc.id }, _sum: { debit: true, credit: true } });
    console.log(`\nNET balance: Dr ${agg._sum.debit} / Cr ${agg._sum.credit} = ${(agg._sum.credit||0) - (agg._sum.debit||0)}`);
  }

  // 2. TCS_PAYABLE account
  const tcsAcc = await prisma.account.findFirst({ where: { code: '2250' }, select: { id: true, name: true } });
  console.log('\n=== TCS_PAYABLE (2250) ===', tcsAcc);
  if (tcsAcc) {
    const agg = await prisma.journalLine.aggregate({ where: { accountId: tcsAcc.id }, _sum: { debit: true, credit: true } });
    console.log(`NET balance: Dr ${agg._sum.debit} / Cr ${agg._sum.credit}`);
  }

  // 3. POs with TDS configured (this period)
  const fyStart = new Date('2026-04-01');
  const today = new Date('2026-04-21T23:59:59');
  const posWithTds = await prisma.purchaseOrder.count({
    where: { tdsPercent: { gt: 0 }, createdAt: { gte: fyStart, lte: today } },
  });
  const posTotal = await prisma.purchaseOrder.count({ where: { createdAt: { gte: fyStart, lte: today } } });
  console.log(`\n=== POs in FY26 (1-Apr-2026 → today): ${posTotal} total, ${posWithTds} have tdsPercent > 0 ===`);

  // 4. VendorPayments with TDS in period
  const vps = await prisma.vendorPayment.findMany({
    where: { paymentDate: { gte: fyStart, lte: today } },
    select: { paymentNo: true, paymentDate: true, amount: true, tdsDeducted: true, tdsSection: true, vendor: { select: { name: true, tdsSection: true } } },
    orderBy: { paymentDate: 'desc' },
    take: 30,
  });
  console.log(`\n=== VendorPayments in period: ${vps.length} ===`);
  for (const v of vps) {
    console.log(`#${v.paymentNo} ${v.paymentDate.toISOString().slice(0,10)} ${v.vendor?.name} amt=${v.amount} tds=${v.tdsDeducted} sec=${v.tdsSection} pct=${v.tdsPercent}`);
  }
  const vpsWithTds = vps.filter(v => v.tdsDeducted > 0);
  console.log(`Of which ${vpsWithTds.length} have tdsDeducted > 0`);

  // 5. ContractorPayments with TDS in period
  const cps = await prisma.contractorPayment.findMany({
    where: { paymentDate: { gte: fyStart, lte: today } },
    select: { paymentDate: true, amount: true, tdsDeducted: true, bill: { select: { billNo: true, contractor: { select: { name: true, tdsSection: true } } } } },
    take: 20,
  });
  console.log(`\n=== ContractorPayments in period: ${cps.length}, with TDS: ${cps.filter(c => c.tdsDeducted > 0).length} ===`);
  for (const c of cps) {
    console.log(`bill#${c.bill?.billNo} ${c.paymentDate.toISOString().slice(0,10)} ${c.bill?.contractor?.name} amt=${c.amount} tds=${c.tdsDeducted}`);
  }

  // 6. ContractorBills with tdsAmount > 0 in period (TDS booked at bill stage)
  const bills = await prisma.contractorBill.findMany({
    where: { billDate: { gte: fyStart, lte: today }, tdsAmount: { gt: 0 } },
    select: { billNo: true, billDate: true, contractor: { select: { name: true } }, subtotal: true, tdsPercent: true, tdsAmount: true, status: true },
    take: 20,
  });
  console.log(`\n=== ContractorBills with tdsAmount > 0 in period: ${bills.length} ===`);
  for (const b of bills) {
    console.log(`bill#${b.billNo} ${b.billDate.toISOString().slice(0,10)} ${b.contractor?.name} sub=${b.subtotal} tds%=${b.tdsPercent} tdsAmt=${b.tdsAmount} ${b.status}`);
  }

  // 7. Invoices with TCS in period
  const invs = await prisma.invoice.findMany({
    where: { invoiceDate: { gte: fyStart, lte: today }, tcsAmount: { gt: 0 } },
    select: { invoiceNo: true, invoiceDate: true, customer: { select: { name: true } }, amount: true, tcsPercent: true, tcsAmount: true, tcsSection: true },
    take: 20,
  });
  console.log(`\n=== Invoices with tcsAmount > 0 in period: ${invs.length} ===`);
  for (const i of invs) {
    console.log(`INV#${i.invoiceNo} ${i.invoiceDate.toISOString().slice(0,10)} ${i.customer?.name} amt=${i.amount} tcs%=${i.tcsPercent} tcsAmt=${i.tcsAmount} sec=${i.tcsSection}`);
  }

  // 8. VendorInvoices with TDS info on them
  const vis = await prisma.vendorInvoice.findMany({
    where: { invoiceDate: { gte: fyStart, lte: today }, tdsAmount: { gt: 0 } },
    select: { invoiceNo: true, invoiceDate: true, vendor: { select: { name: true } }, subtotal: true, tdsPercent: true, tdsAmount: true, tdsSection: true, status: true },
    take: 20,
  });
  console.log(`\n=== VendorInvoices with tdsAmount > 0 in period: ${vis.length} ===`);
  for (const i of vis) {
    console.log(`#${i.invoiceNo} ${i.invoiceDate.toISOString().slice(0,10)} ${i.vendor?.name} sub=${i.subtotal} tds%=${i.tdsPercent} tdsAmt=${i.tdsAmount} sec=${i.tdsSection} ${i.status}`);
  }

  await prisma.$disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
