/**
 * Balance Sheet — Tally-style primary groups (Indian format).
 *
 * Tree levels:
 *   L1  Primary head       (Capital Account, Loans (Liability), Current Liabilities,
 *                           Fixed Assets, Investments, Current Assets, ...)
 *   L2  Sub-group          (Duties & Taxes, Sundry Creditors, Bank Accounts, ...)
 *   L3  Ledger / Party     (TDS Payable, Acme Traders, UBI A/C 4438, Plant & Machinery)
 *   L4  Transactions       (date, narration, dr, cr, running balance)
 *   L5  Full journal entry (the double-entry, showing the other-side accounts)
 *
 * Classification runs purely in the frontend from `subType` + account name.
 * No backend change. When the CoA gets a proper `primaryGroup` field,
 * this classifier becomes a one-line lookup.
 */
import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../../services/api';
import { useHotkeys } from '../../hooks/useHotkeys';
import {
  PageToolbar, TipBanner, FilterBar, FilterLabel, KpiStrip, KpiTile,
  HelpModal, TableContainer, Th, fmtINR,
} from '../../components/accounts/BooksShell';

interface BSAccount {
  id: string;
  code: string;
  name: string;
  subType: string | null;
  balance: number;
}

interface BSSection {
  accounts: BSAccount[];
  total: number;
}

interface BSData {
  asOnDate: string;
  assets: BSSection;
  liabilities: BSSection;
  equity: BSSection;
  liabilitiesAndEquity: number;
  isBalanced: boolean;
}

interface LedgerLine {
  id: string;
  debit: number;
  credit: number;
  narration: string | null;
  costCenter: string | null;
  division: string | null;
  balance: number;
  journal: { id: string; entryNo: number; date: string; narration: string; refType: string | null };
}

interface LedgerData {
  account: { id: string; code: string; name: string; type: string; openingBalance: number };
  openingBalance: number;
  closingBalance: number;
  totalDebit: number;
  totalCredit: number;
  lines: LedgerLine[];
}

interface JournalEntryLine {
  id: string;
  accountId: string;
  debit: number;
  credit: number;
  narration: string | null;
  costCenter: string | null;
  division: string | null;
  account: { code: string; name: string; type: string };
}

interface JournalEntryDetail {
  id: string;
  entryNo: number;
  date: string;
  narration: string;
  refType: string | null;
  refId: string | null;
  isAutoGenerated: boolean;
  isReversed: boolean;
  lines: JournalEntryLine[];
}

// ── Tally primary heads ──────────────────────────────
type PrimaryHead =
  // Liability side
  | 'Capital Account'
  | 'Loans (Liability)'
  | 'Current Liabilities'
  | 'Deferred Taxes'
  | 'Suspense A/c'
  | 'Profit & Loss A/c'
  // Asset side
  | 'Fixed Assets'
  | 'Investments'
  | 'Current Assets'
  | 'Capital Work in Progress'
  | 'Deposits (Asset)'
  | 'Loans & Advances (Asset)'
  | 'Misc. Expenses (Asset)';

const LIAB_ORDER: PrimaryHead[] = [
  'Capital Account', 'Loans (Liability)', 'Current Liabilities',
  'Deferred Taxes', 'Suspense A/c', 'Profit & Loss A/c',
];
const ASSET_ORDER: PrimaryHead[] = [
  'Fixed Assets', 'Investments', 'Current Assets', 'Capital Work in Progress',
  'Deposits (Asset)', 'Loans & Advances (Asset)', 'Misc. Expenses (Asset)',
];

// Preferred sub-group order within each primary (anything not listed goes at the end alphabetically)
const SUB_ORDER: Partial<Record<PrimaryHead, string[]>> = {
  'Capital Account': ['Equity Share Capital', 'Share Premium', 'Capital Redemption Reserve', 'Reserves & Surplus'],
  'Loans (Liability)': ['Bank OD A/c', 'Secured Loans', 'Unsecured Loans', 'Pledge Limit'],
  'Current Liabilities': ['Duties & Taxes', 'Provisions', 'Sundry Creditors', 'Other Current Liabilities'],
  'Current Assets': ['Closing Stock', 'Sundry Debtors', 'Cash-in-hand', 'Bank Accounts', 'Loans & Advances', 'TDS / GST Receivable', 'Prepaid Expenses', 'Other Current Assets'],
};

interface Classified { primary: PrimaryHead; sub: string }
const DIRECT = '(direct)'; // special sub-group for accounts that sit directly under a primary

function classify(a: BSAccount, topType: 'ASSET' | 'LIABILITY' | 'EQUITY'): Classified {
  const st = (a.subType || '').toUpperCase();
  const code = a.code || '';
  const name = a.name.toLowerCase();

  if (topType === 'EQUITY') {
    if (name.includes('share capital') || st.includes('SHARE_CAPITAL')) return { primary: 'Capital Account', sub: 'Equity Share Capital' };
    if (name.includes('premium')) return { primary: 'Capital Account', sub: 'Share Premium' };
    if (name.includes('redemption')) return { primary: 'Capital Account', sub: 'Capital Redemption Reserve' };
    if (name.includes('profit and loss') || name.includes('p&l') || name.includes('p & l') || name.includes('retained')) return { primary: 'Profit & Loss A/c', sub: DIRECT };
    return { primary: 'Capital Account', sub: 'Reserves & Surplus' };
  }

  if (topType === 'LIABILITY') {
    if (st === 'DEFERRED_TAX' || name.includes('deferred tax') || name.includes('deffered tax') || name.includes('deffar tax'))
      return { primary: 'Deferred Taxes', sub: DIRECT };
    if (name.includes('suspense'))
      return { primary: 'Suspense A/c', sub: DIRECT };
    if (name.includes('profit and loss') || name.includes('p&l'))
      return { primary: 'Profit & Loss A/c', sub: DIRECT };

    // Loans (Liability)
    if (name.includes('bank od') || name.includes('cash credit') || name.includes('cc account') || name.includes('overdraft'))
      return { primary: 'Loans (Liability)', sub: 'Bank OD A/c' };
    if (name.includes('pledge'))
      return { primary: 'Loans (Liability)', sub: 'Pledge Limit' };
    if (name.includes('unsecured'))
      return { primary: 'Loans (Liability)', sub: 'Unsecured Loans' };
    if (name.includes('secured') || st === 'LONG_TERM_BORROWING' || st.includes('LONG_TERM') || name.includes('term loan') || name.includes('long-term borrowing'))
      return { primary: 'Loans (Liability)', sub: 'Secured Loans' };
    if (st === 'SHORT_TERM_BORROWING')
      return { primary: 'Loans (Liability)', sub: 'Bank OD A/c' };

    // Current Liabilities → Duties & Taxes
    if (name.includes('gst') || name.includes('cgst') || name.includes('sgst') || name.includes('igst') ||
        name.includes('tds') || name.includes('tcs') || name.includes('duties') || name.includes('cess') ||
        name.includes('excise') || name.includes('professional tax') || name.includes('statutory') ||
        name.includes('pf payable') || name.includes('esi payable'))
      return { primary: 'Current Liabilities', sub: 'Duties & Taxes' };

    // Provisions
    if (st.includes('PROVISION') || name.includes('provision'))
      return { primary: 'Current Liabilities', sub: 'Provisions' };

    // Sundry Creditors (true trade payables)
    if (st === 'TRADE_PAYABLE' || st === 'ACCOUNTS_PAYABLE' ||
        name.includes('sundry creditor') || name.includes('trade payable') ||
        name.includes('creditor') || name.includes('vendor') || name.includes('supplier'))
      return { primary: 'Current Liabilities', sub: 'Sundry Creditors' };

    // Misc current liabilities (salary/wages/audit/expenses payable)
    return { primary: 'Current Liabilities', sub: 'Other Current Liabilities' };
  }

  // ASSET side ───────────────────────────────
  // CWIP
  if (name.includes('cwip') || name.includes('capital work') || name.includes('work-in-progress') || name.includes('work in progress'))
    return { primary: 'Capital Work in Progress', sub: DIRECT };

  // Fixed Assets
  if (st === 'FIXED_ASSET' || st === 'PPE' || st === 'INTANGIBLE' ||
      name.includes('plant') || name.includes('machinery') || name.includes('building') ||
      name.includes('land') || name.includes('vehicle') || name.includes('motor car') ||
      name.includes('equipment') || name.includes('furniture') || name.includes('dumper') ||
      name.includes('weighbridge') || name.includes('computer') ||
      name.includes('software') || name.includes('goodwill') || name.includes('patent') || name.includes('trademark'))
    return { primary: 'Fixed Assets', sub: DIRECT };

  // Investments
  if (st === 'INVESTMENT' || name.includes('investment') || name.includes('shares in') ||
      name.includes('partner in') || name.startsWith('partner '))
    return { primary: 'Investments', sub: DIRECT };

  // Deposits (Asset): FDR, statutory, utility
  if (name.includes('fdr') || name.includes('fixed deposit') ||
      name.includes('security deposit') || name.includes('telephone deposit') ||
      name.includes('electricity deposit') || name.includes('mpeb deposit') ||
      name.includes('pla') || name.includes('against appeal') || name.includes('appeal deposit') ||
      name.includes('bsnl') || name.includes('bharat sanchar'))
    return { primary: 'Deposits (Asset)', sub: DIRECT };

  // Current Assets — sub-grouped
  if (st === 'INVENTORY' || st === 'STOCK' || name.includes('closing stock') || name.includes('inventory') ||
      name.includes('raw material') || name.includes('finished good') || name.includes('wip') || name.includes('stock'))
    return { primary: 'Current Assets', sub: 'Closing Stock' };

  if (st === 'RECEIVABLE' || st === 'ACCOUNTS_RECEIVABLE' || st === 'TRADE_RECEIVABLE' ||
      name.includes('sundry debtor') || name.includes('receivable') || name.includes('customer') || name.includes('debtor'))
    // Separate TDS/GST receivable into their own sub-group
    if (name.includes('tds') || name.includes('gst') || name.includes('cgst') || name.includes('sgst') || name.includes('igst'))
      return { primary: 'Current Assets', sub: 'TDS / GST Receivable' };
    else
      return { primary: 'Current Assets', sub: 'Sundry Debtors' };

  if (name.includes('cash-in-hand') || name.includes('cash in hand') || name.includes('petty cash') ||
      (name.includes('cash') && !name.includes('credit') && !name.includes('bank')))
    return { primary: 'Current Assets', sub: 'Cash-in-hand' };

  if (st === 'BANK' || name.includes('bank') || code === '1001' || code.startsWith('100'))
    return { primary: 'Current Assets', sub: 'Bank Accounts' };

  if (name.includes('prepaid'))
    return { primary: 'Current Assets', sub: 'Prepaid Expenses' };

  // Long-term loans & advances
  if (name.includes('loans atrf') || (name.includes('loan') && (name.includes('long') || name.includes('lt '))))
    return { primary: 'Loans & Advances (Asset)', sub: DIRECT };

  // Short-term advances / loans → Current Assets
  if (name.includes('advance') || name.includes('loan'))
    return { primary: 'Current Assets', sub: 'Loans & Advances' };

  return { primary: 'Current Assets', sub: 'Other Current Assets' };
}

interface SubBucket { name: string; accs: BSAccount[]; total: number }
interface PrimaryBucket { name: PrimaryHead; subs: SubBucket[]; total: number; accountCount: number }

function organize(data: BSData): { liabilities: PrimaryBucket[]; assets: PrimaryBucket[] } {
  // Merge equity + liability accounts into one liability-side pool
  const liabPool: Array<{ a: BSAccount; top: 'LIABILITY' | 'EQUITY' }> = [
    ...data.liabilities.accounts.map(a => ({ a, top: 'LIABILITY' as const })),
    ...data.equity.accounts.map(a => ({ a, top: 'EQUITY' as const })),
  ];

  const liab = groupIntoPrimaries(liabPool.map(({ a, top }) => ({ a, cls: classify(a, top) })), LIAB_ORDER);
  const asst = groupIntoPrimaries(data.assets.accounts.map(a => ({ a, cls: classify(a, 'ASSET') })), ASSET_ORDER);
  return { liabilities: liab, assets: asst };
}

function groupIntoPrimaries(
  items: Array<{ a: BSAccount; cls: Classified }>,
  order: PrimaryHead[],
): PrimaryBucket[] {
  const byPrimary = new Map<PrimaryHead, Map<string, SubBucket>>();
  for (const { a, cls } of items) {
    if (!byPrimary.has(cls.primary)) byPrimary.set(cls.primary, new Map());
    const subMap = byPrimary.get(cls.primary)!;
    if (!subMap.has(cls.sub)) subMap.set(cls.sub, { name: cls.sub, accs: [], total: 0 });
    const sb = subMap.get(cls.sub)!;
    sb.accs.push(a);
    sb.total += a.balance;
  }

  const out: PrimaryBucket[] = [];
  for (const primary of order) {
    const subMap = byPrimary.get(primary);
    if (!subMap) continue;
    // Sort sub-groups by preferred order, then by total desc
    const preferred = SUB_ORDER[primary] || [];
    const subs = Array.from(subMap.values()).sort((x, y) => {
      const xi = preferred.indexOf(x.name);
      const yi = preferred.indexOf(y.name);
      if (xi !== -1 && yi !== -1) return xi - yi;
      if (xi !== -1) return -1;
      if (yi !== -1) return 1;
      if (x.name === DIRECT) return -1;
      if (y.name === DIRECT) return 1;
      return Math.abs(y.total) - Math.abs(x.total);
    });
    // Sort accounts within each sub-group by balance desc
    subs.forEach(s => { s.accs.sort((x, y) => Math.abs(y.balance) - Math.abs(x.balance)); });
    const total = subs.reduce((s, sb) => s + sb.total, 0);
    const accountCount = subs.reduce((s, sb) => s + sb.accs.length, 0);
    out.push({ name: primary, subs, total, accountCount });
  }
  return out;
}

function fmtAmt(n: number): string {
  if (n === 0) return '';
  return Math.abs(n).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function fmtShortDate(s: string): string {
  return new Date(s).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: '2-digit' });
}

export default function BalanceSheet() {
  const navigate = useNavigate();
  const [data, setData] = useState<BSData | null>(null);
  const [loading, setLoading] = useState(false);
  const [asOn, setAsOn] = useState(new Date().toISOString().split('T')[0]);
  const [showHelp, setShowHelp] = useState(false);

  // Tree state — collapsedPrimaries/Subs use inverse semantics (absence = open, default open)
  const [collapsedPrimaries, setCollapsedPrimaries] = useState<Set<string>>(new Set());
  const [collapsedSubs, setCollapsedSubs] = useState<Set<string>>(new Set()); // key: `${primary}::${sub}`
  const [expandedAccounts, setExpandedAccounts] = useState<Set<string>>(new Set());
  const [expandedEntries, setExpandedEntries] = useState<Set<string>>(new Set());
  const [ledgerCache, setLedgerCache] = useState<Map<string, LedgerData>>(new Map());
  const [entryCache, setEntryCache] = useState<Map<string, JournalEntryDetail>>(new Map());
  const [loadingAccounts, setLoadingAccounts] = useState<Set<string>>(new Set());
  const [loadingEntries, setLoadingEntries] = useState<Set<string>>(new Set());
  const [accountErrors, setAccountErrors] = useState<Map<string, string>>(new Map());
  const [entryErrors, setEntryErrors] = useState<Map<string, string>>(new Map());

  const fetchData = useCallback(async () => {
    try {
      setLoading(true);
      const res = await api.get<BSData>('/journal-entries/balance-sheet', { params: { asOn } });
      setData(res.data);
    } catch (err) { console.error('Failed to fetch balance sheet:', err); }
    finally { setLoading(false); }
  }, [asOn]);
  useEffect(() => { fetchData(); }, [fetchData]);

  useEffect(() => {
    setLedgerCache(new Map());
    setEntryCache(new Map());
    setExpandedAccounts(new Set());
    setExpandedEntries(new Set());
    setAccountErrors(new Map());
    setEntryErrors(new Map());
  }, [asOn]);

  const togglePrimary = useCallback((name: string) => {
    setCollapsedPrimaries(s => { const n = new Set(s); if (n.has(name)) n.delete(name); else n.add(name); return n; });
  }, []);
  const toggleSub = useCallback((key: string) => {
    setCollapsedSubs(s => { const n = new Set(s); if (n.has(key)) n.delete(key); else n.add(key); return n; });
  }, []);

  const fetchLedger = useCallback(async (accountId: string) => {
    setLoadingAccounts(s => new Set(s).add(accountId));
    setAccountErrors(m => { const n = new Map(m); n.delete(accountId); return n; });
    try {
      const res = await api.get<LedgerData>(`/journal-entries/ledger/${accountId}`, { params: { to: asOn } });
      setLedgerCache(c => new Map(c).set(accountId, res.data));
    } catch (err: unknown) {
      setAccountErrors(m => new Map(m).set(accountId, err instanceof Error ? err.message : 'Failed to load ledger'));
    } finally {
      setLoadingAccounts(s => { const n = new Set(s); n.delete(accountId); return n; });
    }
  }, [asOn]);

  const toggleAccount = useCallback((accountId: string) => {
    setExpandedAccounts(s => {
      const n = new Set(s);
      if (n.has(accountId)) { n.delete(accountId); return n; }
      n.add(accountId);
      if (!ledgerCache.has(accountId)) fetchLedger(accountId);
      return n;
    });
  }, [ledgerCache, fetchLedger]);

  const fetchEntry = useCallback(async (entryId: string) => {
    setLoadingEntries(s => new Set(s).add(entryId));
    setEntryErrors(m => { const n = new Map(m); n.delete(entryId); return n; });
    try {
      const res = await api.get<JournalEntryDetail>(`/journal-entries/${entryId}`);
      setEntryCache(c => new Map(c).set(entryId, res.data));
    } catch (err: unknown) {
      setEntryErrors(m => new Map(m).set(entryId, err instanceof Error ? err.message : 'Failed to load entry'));
    } finally {
      setLoadingEntries(s => { const n = new Set(s); n.delete(entryId); return n; });
    }
  }, []);

  const toggleEntry = useCallback((entryId: string) => {
    setExpandedEntries(s => {
      const n = new Set(s);
      if (n.has(entryId)) { n.delete(entryId); return n; }
      n.add(entryId);
      if (!entryCache.has(entryId)) fetchEntry(entryId);
      return n;
    });
  }, [entryCache, fetchEntry]);

  const collapseAllDrill = useCallback(() => {
    setExpandedAccounts(new Set());
    setExpandedEntries(new Set());
  }, []);

  const openLedger = useCallback((accountId: string) => {
    navigate(`/accounts/ledger?accountId=${accountId}&to=${asOn}`);
  }, [navigate, asOn]);

  useHotkeys([
    { key: 't', handler: e => { e.preventDefault(); setAsOn(new Date().toISOString().split('T')[0]); } },
    { key: 'c', handler: e => { e.preventDefault(); collapseAllDrill(); } },
    { key: '?', shift: true, handler: e => { e.preventDefault(); setShowHelp(h => !h); } },
    { key: 'Escape', allowInInputs: true, handler: () => { if (showHelp) setShowHelp(false); } },
  ]);

  const organized = useMemo(() => (data ? organize(data) : null), [data]);

  const fmtAsOnLabel = (d: string) => new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' });

  const renderEntryDetail = (entryId: string) => {
    const isLoading = loadingEntries.has(entryId);
    const error = entryErrors.get(entryId);
    const entry = entryCache.get(entryId);
    return (
      <div className="pl-8 pr-3 py-2 bg-indigo-50/50 border-l-2 border-indigo-400">
        {isLoading && <div className="text-[10px] text-slate-500 uppercase tracking-widest">Loading journal entry…</div>}
        {error && <div className="text-[10px] text-rose-600">Failed: {error}. <button onClick={() => fetchEntry(entryId)} className="underline">Retry</button></div>}
        {entry && !isLoading && !error && (
          <>
            <div className="flex items-center gap-3 mb-1 text-[10px] text-slate-600 flex-wrap">
              <span className="font-mono font-bold">#{entry.entryNo}</span>
              <span>{fmtShortDate(entry.date)}</span>
              {entry.refType && <span className="px-1.5 py-0.5 border border-slate-300 bg-white text-slate-600 font-mono">{entry.refType}</span>}
              {entry.isAutoGenerated && <span className="text-slate-400 uppercase tracking-widest">auto</span>}
              {entry.isReversed && <span className="text-rose-600 font-bold uppercase tracking-widest">reversed</span>}
              <span className="flex-1 italic text-slate-500 truncate" title={entry.narration}>{entry.narration}</span>
            </div>
            <table className="w-full text-[11px] border border-slate-200 bg-white">
              <thead>
                <tr className="bg-slate-100 text-slate-600">
                  <th className="px-2 py-1 text-left font-semibold">Account</th>
                  <th className="px-2 py-1 text-left font-semibold">Div</th>
                  <th className="px-2 py-1 text-left font-semibold">Narration</th>
                  <th className="px-2 py-1 text-right font-semibold w-28">Debit</th>
                  <th className="px-2 py-1 text-right font-semibold w-28">Credit</th>
                </tr>
              </thead>
              <tbody>
                {entry.lines.map(l => (
                  <tr key={l.id} className="border-t border-slate-100">
                    <td className="px-2 py-1">
                      <span className="font-mono text-[10px] text-slate-400 mr-1">{l.account.code}</span>{l.account.name}
                    </td>
                    <td className="px-2 py-1 text-[10px] text-slate-500">{l.division || '--'}</td>
                    <td className="px-2 py-1 text-slate-600 truncate max-w-sm" title={l.narration || ''}>{l.narration || ''}</td>
                    <td className="px-2 py-1 text-right font-mono tabular-nums">{fmtAmt(l.debit)}</td>
                    <td className="px-2 py-1 text-right font-mono tabular-nums">{fmtAmt(l.credit)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </>
        )}
      </div>
    );
  };

  const renderAccountLedger = (accountId: string) => {
    const isLoading = loadingAccounts.has(accountId);
    const error = accountErrors.get(accountId);
    const ledger = ledgerCache.get(accountId);
    return (
      <div className="pl-6 pr-2 py-2 bg-slate-50 border-l-2 border-blue-400">
        <div className="flex items-center justify-between mb-1 flex-wrap gap-2">
          <div className="text-[10px] text-slate-500 uppercase tracking-widest">
            Ledger up to {fmtAsOnLabel(asOn)}
            {ledger && (
              <>
                {' · opening '}<span className="font-mono tabular-nums text-slate-700">{fmtAmt(ledger.openingBalance) || '0.00'}</span>
                {' · closing '}<span className="font-mono tabular-nums font-semibold text-slate-800">{fmtAmt(ledger.closingBalance) || '0.00'}</span>
                {' · '}<span className="text-slate-400">{ledger.lines.length} txns</span>
              </>
            )}
          </div>
          <button onClick={e => { e.stopPropagation(); openLedger(accountId); }} className="text-[10px] text-blue-600 hover:underline">
            open in full ledger page &rarr;
          </button>
        </div>
        {isLoading && <div className="space-y-1 my-2">{[0, 1, 2].map(i => <div key={i} className="h-5 bg-slate-200 animate-pulse" />)}</div>}
        {error && <div className="text-[10px] text-rose-600 py-2">Failed: {error}. <button onClick={() => fetchLedger(accountId)} className="underline">Retry</button></div>}
        {ledger && !isLoading && !error && (
          <>
            {ledger.lines.length === 0 ? (
              <div className="text-[10px] text-slate-400 uppercase tracking-widest py-2">No transactions up to this date</div>
            ) : (
              <table className="w-full text-[11px] border border-slate-200 bg-white">
                <thead>
                  <tr className="bg-slate-100 text-slate-600">
                    <th className="px-2 py-1 text-left font-semibold w-6"></th>
                    <th className="px-2 py-1 text-left font-semibold w-20">Date</th>
                    <th className="px-2 py-1 text-left font-semibold w-16">Entry</th>
                    <th className="px-2 py-1 text-left font-semibold">Narration</th>
                    <th className="px-2 py-1 text-left font-semibold w-20">Ref</th>
                    <th className="px-2 py-1 text-right font-semibold w-24">Debit</th>
                    <th className="px-2 py-1 text-right font-semibold w-24">Credit</th>
                    <th className="px-2 py-1 text-right font-semibold w-28">Balance</th>
                  </tr>
                </thead>
                <tbody>
                  {ledger.lines.map(line => {
                    const isOpen = expandedEntries.has(line.journal.id);
                    return (
                      <React.Fragment key={line.id}>
                        <tr onClick={() => toggleEntry(line.journal.id)} className={`border-t border-slate-100 cursor-pointer hover:bg-blue-50/80 ${isOpen ? 'bg-indigo-50/80' : ''}`}>
                          <td className="px-2 py-1 text-[10px] text-slate-500 font-mono">{isOpen ? '▾' : '▸'}</td>
                          <td className="px-2 py-1">{fmtShortDate(line.journal.date)}</td>
                          <td className="px-2 py-1 font-mono text-[10px] text-slate-500">#{line.journal.entryNo}</td>
                          <td className="px-2 py-1 text-slate-700 truncate max-w-md" title={line.journal.narration}>
                            {line.journal.narration}
                            {line.narration && line.narration !== line.journal.narration && <span className="text-slate-400 ml-1">({line.narration})</span>}
                          </td>
                          <td className="px-2 py-1 text-[10px] text-slate-500">{line.journal.refType || '--'}</td>
                          <td className="px-2 py-1 text-right font-mono tabular-nums">{fmtAmt(line.debit)}</td>
                          <td className="px-2 py-1 text-right font-mono tabular-nums">{fmtAmt(line.credit)}</td>
                          <td className={`px-2 py-1 text-right font-mono tabular-nums font-medium ${line.balance < 0 ? 'text-rose-600' : 'text-slate-800'}`}>
                            {line.balance < 0 ? '-' : ''}{fmtAmt(line.balance)}
                          </td>
                        </tr>
                        {isOpen && <tr><td colSpan={8} className="p-0">{renderEntryDetail(line.journal.id)}</td></tr>}
                      </React.Fragment>
                    );
                  })}
                </tbody>
                <tfoot>
                  <tr className="bg-slate-100 text-[10px] text-slate-700 border-t border-slate-200">
                    <td colSpan={5} className="px-2 py-1 text-right uppercase tracking-widest font-bold">Totals</td>
                    <td className="px-2 py-1 text-right font-mono tabular-nums font-bold">{fmtAmt(ledger.totalDebit)}</td>
                    <td className="px-2 py-1 text-right font-mono tabular-nums font-bold">{fmtAmt(ledger.totalCredit)}</td>
                    <td className="px-2 py-1 text-right font-mono tabular-nums font-bold">{fmtAmt(ledger.closingBalance) || '0.00'}</td>
                  </tr>
                </tfoot>
              </table>
            )}
            {ledger.lines.length >= 500 && <div className="mt-1 text-[10px] text-amber-700">Showing first 500 lines. Open full ledger for more.</div>}
          </>
        )}
      </div>
    );
  };

  // ── Primary → Sub → Account rendering ──
  const renderAccountRow = (a: BSAccount, indent: number) => {
    const isOpen = expandedAccounts.has(a.id);
    return (
      <React.Fragment key={a.id}>
        <tr onClick={() => toggleAccount(a.id)} className={`border-b border-slate-100 text-[11px] cursor-pointer hover:bg-blue-50 ${isOpen ? 'bg-blue-50/70' : ''}`}>
          <td className="px-3 py-1 text-slate-600 border-r border-slate-100" style={{ paddingLeft: `${indent}px` }}>
            <span className="inline-block w-4 text-slate-400 font-mono text-[10px]">{isOpen ? '▾' : '▸'}</span>
            <span className="font-mono text-[10px] text-slate-400 mr-2">{a.code}</span>{a.name}
          </td>
          <td className={`px-3 py-1 text-right font-mono tabular-nums ${isOpen ? 'text-slate-800 font-semibold' : 'text-slate-700'}`}>{fmtINR(a.balance)}</td>
        </tr>
        {isOpen && <tr><td colSpan={2} className="p-0">{renderAccountLedger(a.id)}</td></tr>}
      </React.Fragment>
    );
  };

  const renderPrimary = (p: PrimaryBucket) => {
    const isPrimaryCollapsed = collapsedPrimaries.has(p.name);
    return (
      <React.Fragment key={p.name}>
        {/* Primary head row */}
        <tr className="bg-slate-100 border-b border-slate-300 cursor-pointer hover:bg-slate-200" onClick={() => togglePrimary(p.name)}>
          <td className="px-3 py-1.5 text-[11px] font-bold text-slate-800 border-r border-slate-300">
            <span className="inline-block w-4 text-slate-500 font-mono text-[10px]">{isPrimaryCollapsed ? '▸' : '▾'}</span>
            {p.name}
            <span className="ml-2 text-[10px] text-slate-500 font-normal">({p.accountCount})</span>
          </td>
          <td className="px-3 py-1.5 text-right font-mono tabular-nums text-slate-900 font-bold">{fmtINR(p.total)}</td>
        </tr>
        {!isPrimaryCollapsed && p.subs.map(sb => {
          const subKey = `${p.name}::${sb.name}`;
          const isSubCollapsed = collapsedSubs.has(subKey);
          const isDirect = sb.name === DIRECT;
          return (
            <React.Fragment key={subKey}>
              {!isDirect && (
                <tr className="border-b border-slate-100 bg-slate-50 cursor-pointer hover:bg-slate-100" onClick={() => toggleSub(subKey)}>
                  <td className="px-3 py-1 text-[11px] text-slate-700 border-r border-slate-100" style={{ paddingLeft: '32px' }}>
                    <span className="inline-block w-4 text-slate-400 font-mono text-[10px]">{isSubCollapsed ? '▸' : '▾'}</span>
                    <span className="font-medium">{sb.name}</span>
                    <span className="ml-2 text-[10px] text-slate-400">({sb.accs.length})</span>
                  </td>
                  <td className="px-3 py-1 text-right font-mono tabular-nums text-slate-700 font-semibold">{fmtINR(sb.total)}</td>
                </tr>
              )}
              {(isDirect || !isSubCollapsed) && sb.accs.map(a => renderAccountRow(a, isDirect ? 32 : 56))}
            </React.Fragment>
          );
        })}
      </React.Fragment>
    );
  };

  const anyDrillOpen = expandedAccounts.size > 0 || expandedEntries.size > 0;

  return (
    <div className="min-h-screen bg-slate-50">
      <div className="p-3 md:p-6 space-y-0">
        <PageToolbar
          title="Balance Sheet"
          subtitle="Tally primary groups · drill any row"
          statusBadge={data && (
            <span className={`text-[9px] font-bold uppercase px-1.5 py-0.5 border ${data.isBalanced ? 'border-emerald-400/50 bg-emerald-500/20 text-emerald-200' : 'border-red-400/50 bg-red-500/20 text-red-200'}`}>
              {data.isBalanced ? 'Balanced' : 'Out of Balance'}
            </span>
          )}
        >
          <button onClick={collapseAllDrill} disabled={!anyDrillOpen}
            className="px-2 py-1 border border-slate-600 text-slate-300 text-[10px] uppercase tracking-widest hover:bg-slate-700 disabled:opacity-40 disabled:cursor-not-allowed"
            title="Collapse all open drill-downs (C)">Collapse all</button>
          <button onClick={() => setShowHelp(true)} className="w-6 h-6 border border-slate-600 text-slate-300 text-xs font-bold hover:bg-slate-700" title="Shortcuts (?)">?</button>
        </PageToolbar>

        <TipBanner storageKey="bs_tip_tally_v1">
          Tip: click a primary head (Capital Account, Current Liabilities, etc.) to collapse it. Click a sub-group
          (Duties &amp; Taxes, Sundry Creditors, Bank Accounts) to collapse its ledgers. Click a ledger to open its
          transactions inline. Click a transaction to see the full journal entry.
        </TipBanner>

        <FilterBar>
          <div>
            <FilterLabel>As on</FilterLabel>
            <input type="date" value={asOn} onChange={e => setAsOn(e.target.value)}
              className="border border-slate-300 px-2.5 py-1.5 text-xs bg-white focus:outline-none focus:ring-1 focus:ring-slate-400" />
          </div>
          <div className="text-[10px] text-slate-500 mt-4 uppercase tracking-widest">As on {fmtAsOnLabel(asOn)}</div>
        </FilterBar>

        {loading && <div className="text-xs text-slate-400 uppercase tracking-widest py-4 px-4">Loading balance sheet...</div>}

        {data && organized && !loading && (
          <>
            <KpiStrip cols={4}>
              <KpiTile label="Liabilities + Equity" value={fmtINR(data.liabilitiesAndEquity) || '\u20B90.00'} color="rose" valueClass="text-rose-700" />
              <KpiTile label="Total Assets" value={fmtINR(data.assets.total) || '\u20B90.00'} color="blue" valueClass="text-blue-700" />
              <KpiTile label="Difference" value={fmtINR(data.assets.total - data.liabilitiesAndEquity) || '\u20B90.00'} color={data.isBalanced ? 'emerald' : 'red'} valueClass={data.isBalanced ? 'text-slate-800' : 'text-red-700'} />
              <KpiTile label="Net P&L (period)" value="—" color="violet" last />
            </KpiStrip>

            <TableContainer>
              <table className="w-full text-xs">
                <thead>
                  <tr className="bg-slate-800 text-white">
                    <Th>Particulars</Th>
                    <Th align="right" last>Amount (₹)</Th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="bg-slate-900 text-white border-b-2 border-slate-700">
                    <td colSpan={2} className="px-3 py-2 text-[11px] font-bold uppercase tracking-widest">Liabilities</td>
                  </tr>
                  {organized.liabilities.map(renderPrimary)}
                  <tr className="bg-slate-700 text-white border-b-2 border-slate-900 font-semibold">
                    <td className="px-3 py-2 text-[11px] uppercase tracking-widest">Total — Liabilities &amp; Equity</td>
                    <td className="px-3 py-2 text-right font-mono tabular-nums">{fmtINR(data.liabilitiesAndEquity)}</td>
                  </tr>

                  <tr className="bg-slate-900 text-white border-b-2 border-slate-700">
                    <td colSpan={2} className="px-3 py-2 text-[11px] font-bold uppercase tracking-widest">Assets</td>
                  </tr>
                  {organized.assets.map(renderPrimary)}
                  <tr className="bg-slate-700 text-white border-b-2 border-slate-900 font-semibold">
                    <td className="px-3 py-2 text-[11px] uppercase tracking-widest">Total — Assets</td>
                    <td className="px-3 py-2 text-right font-mono tabular-nums">{fmtINR(data.assets.total)}</td>
                  </tr>
                </tbody>
              </table>
            </TableContainer>

            {!data.isBalanced && (
              <div className="bg-red-50 border-x border-b border-red-200 -mx-3 md:-mx-6 px-4 py-2 text-[11px] text-red-700">
                Balance Sheet is out of balance by {fmtINR(Math.abs(data.assets.total - data.liabilitiesAndEquity))}. Check for unposted or orphaned journal entries.
              </div>
            )}
          </>
        )}
      </div>

      <HelpModal
        open={showHelp}
        onClose={() => setShowHelp(false)}
        entries={[
          ['T', 'As on today'],
          ['C', 'Collapse all drill-downs'],
          ['Click primary', 'Collapse / expand primary group'],
          ['Click sub-group', 'Collapse / expand sub-group'],
          ['Click ledger', 'Open transactions inline'],
          ['Click transaction', 'Open full journal entry inline'],
          ['Esc', 'Close modal'],
          ['?', 'Show this help'],
        ]}
      />
    </div>
  );
}
