import React, { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import api from '../../services/api';
import { ComboAccount } from '../../components/accounts/AccountCombobox';
import NewJournalEntryModal from '../../components/accounts/NewJournalEntryModal';
import { useHotkeys } from '../../hooks/useHotkeys';
import { Division, DIVISION_COLORS } from '../../constants/divisions';
import {
  PageToolbar, TipBanner, FilterBar, SecondaryFilterBar, FilterLabel,
  PresetButtons, DateRangeInputs, DivisionSegmented, KpiStrip, KpiTile,
  DivisionSplitBar, HelpModal, TableContainer, Th, RefTypeChips,
  RefType, DivisionFilter, computePreset, fmtINR, fmtDate,
} from '../../components/accounts/BooksShell';

interface JELine {
  account: { code: string; name: string };
  debit: number;
  credit: number;
  costCenter: string | null;
  division: string | null;
}

interface DBEntry {
  id: string;
  entryNo: number;
  date: string;
  narration: string;
  refType: string | null;
  isAutoGenerated: boolean;
  isReversed: boolean;
  lines: JELine[];
}

interface DBData {
  from: string | null;
  to: string | null;
  entries: DBEntry[];
  count: number;
  totalDebit: number;
  totalCredit: number;
}

export default function DayBook() {
  const today = new Date().toISOString().split('T')[0];
  const [accounts, setAccounts] = useState<ComboAccount[]>([]);
  const [dateRange, setDateRange] = useState({ from: today, to: today });
  const [divisionFilter, setDivisionFilter] = useState<DivisionFilter>('ALL');
  const [data, setData] = useState<DBData | null>(null);
  const [loading, setLoading] = useState(false);

  const [narrationSearch, setNarrationSearch] = useState('');
  const [refTypeFilter, setRefTypeFilter] = useState<Set<RefType>>(new Set());
  const [expanded, setExpanded] = useState<Set<string>>(new Set());

  const [newEntryOpen, setNewEntryOpen] = useState(false);
  const [showHelp, setShowHelp] = useState(false);
  const narrationRef = useRef<HTMLInputElement>(null);

  const fetchAccounts = useCallback(async () => {
    try {
      const res = await api.get<ComboAccount[]>('/chart-of-accounts');
      setAccounts(res.data);
    } catch (err) { console.error(err); }
  }, []);
  useEffect(() => { fetchAccounts(); }, [fetchAccounts]);

  const fetchData = useCallback(async () => {
    if (!dateRange.from || !dateRange.to) return;
    try {
      setLoading(true);
      const params: Record<string, string> = { from: dateRange.from, to: dateRange.to };
      if (divisionFilter !== 'ALL') params.division = divisionFilter;
      const res = await api.get<DBData>('/journal-entries/daybook', { params });
      setData(res.data);
    } catch (err) { console.error('Failed to fetch daybook:', err); }
    finally { setLoading(false); }
  }, [dateRange, divisionFilter]);
  useEffect(() => { fetchData(); }, [fetchData]);

  const filtered = useMemo(() => {
    if (!data) return { entries: [] as DBEntry[], totalDebit: 0, totalCredit: 0 };
    const nq = narrationSearch.trim().toLowerCase();
    const out = data.entries.filter(e => {
      if (nq && !e.narration.toLowerCase().includes(nq)) return false;
      if (refTypeFilter.size > 0 && (!e.refType || !refTypeFilter.has(e.refType as RefType))) return false;
      return true;
    });
    const totalDebit = out.reduce((s, e) => s + e.lines.reduce((ls, l) => ls + l.debit, 0), 0);
    const totalCredit = out.reduce((s, e) => s + e.lines.reduce((ls, l) => ls + l.credit, 0), 0);
    return { entries: out, totalDebit, totalCredit };
  }, [data, narrationSearch, refTypeFilter]);

  const flatLines = useMemo(
    () => filtered.entries.flatMap(e => e.lines.map(l => ({ division: l.division, debit: l.debit, credit: l.credit }))),
    [filtered.entries]
  );

  const moveDate = useCallback((days: number) => {
    const d = new Date(dateRange.from);
    d.setDate(d.getDate() + days);
    const iso = d.toISOString().split('T')[0];
    setDateRange({ from: iso, to: iso });
  }, [dateRange.from]);

  const clearAllFilters = useCallback(() => { setNarrationSearch(''); setRefTypeFilter(new Set()); }, []);
  const toggleExpand = (id: string) => setExpanded(s => { const n = new Set(s); if (n.has(id)) n.delete(id); else n.add(id); return n; });

  useHotkeys([
    { key: 'f', ctrl: true, handler: e => { e.preventDefault(); narrationRef.current?.focus(); } },
    { key: 'n', handler: e => { e.preventDefault(); setNewEntryOpen(true); } },
    { key: 't', handler: e => { e.preventDefault(); setDateRange({ from: today, to: today }); } },
    { key: 'ArrowLeft', handler: e => { e.preventDefault(); moveDate(-1); } },
    { key: 'ArrowRight', handler: e => { e.preventDefault(); moveDate(1); } },
    { key: 'm', handler: e => { e.preventDefault(); setDateRange(computePreset('month')); } },
    { key: '0', handler: e => { e.preventDefault(); setDivisionFilter('ALL'); } },
    { key: '1', handler: e => { e.preventDefault(); setDivisionFilter('SUGAR'); } },
    { key: '2', handler: e => { e.preventDefault(); setDivisionFilter('POWER'); } },
    { key: '3', handler: e => { e.preventDefault(); setDivisionFilter('ETHANOL'); } },
    { key: '?', shift: true, handler: e => { e.preventDefault(); setShowHelp(h => !h); } },
    { key: 'Escape', allowInInputs: true, handler: () => {
      if (showHelp) { setShowHelp(false); return; }
      if (newEntryOpen) return;
      clearAllFilters();
    } },
  ]);

  const toggleRefType = (rt: RefType) => setRefTypeFilter(s => {
    const n = new Set(s); if (n.has(rt)) n.delete(rt); else n.add(rt); return n;
  });

  const net = filtered.totalDebit - filtered.totalCredit;
  const balanced = Math.abs(net) < 0.01;

  return (
    <div className="min-h-screen bg-slate-50">
      <div className="p-3 md:p-6 space-y-0">
        <PageToolbar
          title="Day Book"
          subtitle="Daily journal register · keyboard-first · expandable lines"
          statusBadge={data && (
            <span className={`text-[9px] font-bold uppercase px-1.5 py-0.5 border ${balanced ? 'border-emerald-400/50 bg-emerald-500/20 text-emerald-200' : 'border-red-400/50 bg-red-500/20 text-red-200'}`}>
              {balanced ? 'Balanced' : 'Out of Balance'}
            </span>
          )}
        >
          <button onClick={() => setNewEntryOpen(true)} className="px-3 py-1 bg-blue-600 text-white text-[11px] font-medium hover:bg-blue-700" title="Post a new journal entry (N)">+ New Entry (N)</button>
          <button onClick={() => setShowHelp(true)} className="w-6 h-6 border border-slate-600 text-slate-300 text-xs font-bold hover:bg-slate-700" title="Keyboard shortcuts (?)">?</button>
        </PageToolbar>

        <TipBanner storageKey="daybook_tip_dismissed">
          Tip: use <kbd className="px-1 bg-white border border-amber-300 font-mono">←</kbd>/<kbd className="px-1 bg-white border border-amber-300 font-mono">→</kbd> to walk days,
          <kbd className="ml-1 px-1 bg-white border border-amber-300 font-mono">N</kbd> for new entry,
          <kbd className="ml-1 px-1 bg-white border border-amber-300 font-mono">?</kbd> for all shortcuts.
        </TipBanner>

        <FilterBar>
          <div>
            <FilterLabel>Walk</FilterLabel>
            <div className="flex gap-1">
              <button onClick={() => moveDate(-1)} className="px-2 py-1.5 bg-white border border-slate-300 text-[10px] font-medium hover:bg-slate-50" title="Previous day (←)">← Prev</button>
              <button onClick={() => setDateRange({ from: today, to: today })} className="px-2 py-1.5 bg-white border border-slate-300 text-[10px] font-medium hover:bg-slate-50" title="Today (T)">Today</button>
              <button onClick={() => moveDate(1)} className="px-2 py-1.5 bg-white border border-slate-300 text-[10px] font-medium hover:bg-slate-50" title="Next day (→)">Next →</button>
            </div>
          </div>
          <PresetButtons onPreset={p => setDateRange(computePreset(p))} />
          <DateRangeInputs from={dateRange.from} to={dateRange.to} onChange={setDateRange} />
          <DivisionSegmented value={divisionFilter} onChange={setDivisionFilter} />
        </FilterBar>

        {data && (
          <SecondaryFilterBar>
            <div className="flex-1 min-w-[200px]">
              <FilterLabel>Narration (Ctrl+F)</FilterLabel>
              <input ref={narrationRef} type="text" value={narrationSearch} onChange={e => setNarrationSearch(e.target.value)}
                placeholder="Search narration…"
                className="w-full border border-slate-300 px-2.5 py-1.5 text-xs focus:outline-none focus:ring-1 focus:ring-slate-400" />
            </div>
            <RefTypeChips value={refTypeFilter} onToggle={toggleRefType} />
          </SecondaryFilterBar>
        )}

        {loading && <div className="text-xs text-slate-400 uppercase tracking-widest py-4 px-4">Loading day book...</div>}

        {data && !loading && (
          <>
            <KpiStrip cols={5}>
              <KpiTile label="Entries" value={filtered.entries.length} sub={`${data.from} → ${data.to}`} color="slate" />
              <KpiTile label="Total Debit" value={fmtINR(filtered.totalDebit) || '\u20B90.00'} color="emerald" valueClass="text-emerald-700" />
              <KpiTile label="Total Credit" value={fmtINR(filtered.totalCredit) || '\u20B90.00'} color="rose" valueClass="text-rose-700" />
              <KpiTile label="Net (should be 0)" value={net < 0 ? '-' + fmtINR(Math.abs(net)) : fmtINR(net) || '\u20B90.00'} color="amber" valueClass={balanced ? 'text-slate-800' : 'text-red-700'} />
              <KpiTile label="Auto-Generated" value={filtered.entries.filter(e => e.isAutoGenerated).length} sub="system entries" color="indigo" last />
            </KpiStrip>

            <DivisionSplitBar lines={flatLines} />

            <TableContainer>
              <table className="w-full text-xs">
                <thead>
                  <tr className="bg-slate-800 text-white">
                    <Th>Date</Th>
                    <Th>Entry #</Th>
                    <Th>Narration</Th>
                    <Th>Ref</Th>
                    <Th>Flags</Th>
                    <Th align="right">Debit</Th>
                    <Th align="right" last>Credit</Th>
                  </tr>
                </thead>
                <tbody>
                  {filtered.entries.map((e, i) => {
                    const dTotal = e.lines.reduce((s, l) => s + l.debit, 0);
                    const cTotal = e.lines.reduce((s, l) => s + l.credit, 0);
                    const isOpen = expanded.has(e.id);
                    return (
                      <React.Fragment key={e.id}>
                        <tr onClick={() => toggleExpand(e.id)}
                          className={`cursor-pointer hover:bg-blue-50 border-b border-slate-100 ${i % 2 ? 'bg-slate-50/50' : ''} ${e.isReversed ? 'opacity-50 line-through' : ''}`}>
                          <td className="px-3 py-1.5 text-slate-600 border-r border-slate-100">{fmtDate(e.date)}</td>
                          <td className="px-3 py-1.5 font-mono text-[10px] text-slate-500 border-r border-slate-100">
                            <span className="mr-1 text-slate-400">{isOpen ? '▾' : '▸'}</span>#{e.entryNo}
                          </td>
                          <td className="px-3 py-1.5 text-slate-700 border-r border-slate-100">{e.narration}</td>
                          <td className="px-3 py-1.5 text-[10px] text-slate-500 border-r border-slate-100">{e.refType || '--'}</td>
                          <td className="px-3 py-1.5 text-[10px] border-r border-slate-100">
                            {e.isAutoGenerated && <span className="text-[9px] font-bold uppercase px-1 py-0.5 border border-indigo-300 bg-indigo-50 text-indigo-700 mr-1">AUTO</span>}
                            {e.isReversed && <span className="text-[9px] font-bold uppercase px-1 py-0.5 border border-red-300 bg-red-50 text-red-700">REV</span>}
                          </td>
                          <td className="px-3 py-1.5 text-right font-mono tabular-nums text-slate-700 border-r border-slate-100">{fmtINR(dTotal)}</td>
                          <td className="px-3 py-1.5 text-right font-mono tabular-nums text-slate-700">{fmtINR(cTotal)}</td>
                        </tr>
                        {isOpen && e.lines.map((l, li) => (
                          <tr key={`${e.id}-${li}`} className="bg-slate-50/80 border-b border-slate-100 text-[11px]">
                            <td colSpan={2}></td>
                            <td className="px-3 py-1 pl-8 text-slate-600 border-r border-slate-100">
                              <span className="font-mono text-[10px] text-slate-400">{l.account.code}</span> · {l.account.name}
                              {l.costCenter && <span className="text-[10px] text-slate-400 ml-2">[{l.costCenter}]</span>}
                            </td>
                            <td className="px-3 py-1 border-r border-slate-100"></td>
                            <td className="px-3 py-1 text-[10px] border-r border-slate-100">
                              {l.division && (
                                <span className={`inline-block w-2 h-2 mr-1 align-middle ${DIVISION_COLORS[l.division as Division] || 'bg-slate-300'}`}></span>
                              )}
                              <span className="text-slate-500">{l.division || '--'}</span>
                            </td>
                            <td className="px-3 py-1 text-right font-mono tabular-nums text-emerald-700 border-r border-slate-100">{fmtINR(l.debit)}</td>
                            <td className="px-3 py-1 text-right font-mono tabular-nums text-rose-700">{fmtINR(l.credit)}</td>
                          </tr>
                        ))}
                      </React.Fragment>
                    );
                  })}
                  {filtered.entries.length === 0 && (
                    <tr><td colSpan={7} className="text-center py-8 text-xs text-slate-400 uppercase tracking-widest">No entries in range</td></tr>
                  )}
                </tbody>
                <tfoot>
                  <tr className="bg-slate-800 text-white font-semibold">
                    <td colSpan={5} className="px-3 py-2 text-right text-[10px] uppercase tracking-widest border-r border-slate-700">Totals</td>
                    <td className="px-3 py-2 text-right font-mono tabular-nums border-r border-slate-700">{fmtINR(filtered.totalDebit)}</td>
                    <td className="px-3 py-2 text-right font-mono tabular-nums">{fmtINR(filtered.totalCredit)}</td>
                  </tr>
                </tfoot>
              </table>
            </TableContainer>
          </>
        )}
      </div>

      <HelpModal
        open={showHelp}
        onClose={() => setShowHelp(false)}
        entries={[
          ['← / →', 'Previous / next day'],
          ['Ctrl+F', 'Focus narration filter'],
          ['N', 'New journal entry'],
          ['T', 'Today'],
          ['M', 'This month'],
          ['0', 'Division: All'],
          ['1 / 2 / 3', 'Division: Sugar / Power / Ethanol'],
          ['Click row', 'Expand / collapse lines'],
          ['Esc', 'Close modal / clear filters'],
          ['?', 'Show this help'],
        ]}
      />

      <NewJournalEntryModal
        open={newEntryOpen}
        accounts={accounts}
        initialDivision={divisionFilter !== 'ALL' ? divisionFilter : undefined}
        onClose={() => setNewEntryOpen(false)}
        onCreated={() => fetchData()}
        onAccountCreated={() => fetchAccounts()}
      />
    </div>
  );
}
