import React, { useState, useEffect, useCallback } from 'react';
import api from '../../services/api';

interface DayBookEntry {
  id: string;
  entryNo: number;
  date: string;
  narration: string;
  refType: string | null;
  isAutoGenerated: boolean;
  isReversed: boolean;
  lines: {
    account: { code: string; name: string };
    debit: number;
    credit: number;
    costCenter: string | null;
  }[];
}

interface DayBookData {
  date: string;
  entries: DayBookEntry[];
  count: number;
  totalDebit: number;
  totalCredit: number;
}

export default function DayBook() {
  const [date, setDate] = useState(new Date().toISOString().split('T')[0]);
  const [data, setData] = useState<DayBookData | null>(null);
  const [loading, setLoading] = useState(false);

  const fetchData = useCallback(async () => {
    try {
      setLoading(true);
      const res = await api.get<DayBookData>('/journal-entries/daybook', { params: { date } });
      setData(res.data);
    } catch (err) {
      console.error('Failed to fetch daybook:', err);
    } finally {
      setLoading(false);
    }
  }, [date]);

  useEffect(() => { fetchData(); }, [fetchData]);

  const fmtCurrency = (n: number): string => {
    if (n === 0) return '';
    return '₹' + n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  };

  const moveDate = (days: number) => {
    const d = new Date(date);
    d.setDate(d.getDate() + days);
    setDate(d.toISOString().split('T')[0]);
  };

  return (
    <div className="p-6 space-y-4">
      <h1 className="text-2xl font-bold text-gray-800">Day Book</h1>

      {/* Date Navigation */}
      <div className="flex gap-3 items-center">
        <button onClick={() => moveDate(-1)} className="px-3 py-1.5 bg-gray-100 rounded hover:bg-gray-200 text-sm">← Prev</button>
        <input
          type="date"
          value={date}
          onChange={e => setDate(e.target.value)}
          className="border rounded px-3 py-1.5 text-sm"
        />
        <button onClick={() => moveDate(1)} className="px-3 py-1.5 bg-gray-100 rounded hover:bg-gray-200 text-sm">Next →</button>
        <button
          onClick={() => setDate(new Date().toISOString().split('T')[0])}
          className="px-3 py-1.5 bg-blue-100 text-blue-700 rounded text-sm hover:bg-blue-200"
        >
          Today
        </button>
        {data && (
          <span className="text-sm text-gray-500 ml-2">
            {data.count} entries | Debit: {fmtCurrency(data.totalDebit)} | Credit: {fmtCurrency(data.totalCredit)}
          </span>
        )}
      </div>

      {loading && <div className="text-gray-500 text-sm">Loading...</div>}

      {data && !loading && (
        <div className="space-y-3">
          {data.entries.map(entry => (
            <div key={entry.id} className={`bg-white rounded-lg border ${entry.isReversed ? 'opacity-50 border-red-200' : ''}`}>
              <div className="px-4 py-2 bg-gray-50 border-b flex items-center gap-3">
                <span className="font-mono text-xs text-gray-400">#{entry.entryNo}</span>
                <span className="font-medium text-sm flex-1">{entry.narration}</span>
                {entry.refType && <span className="text-xs px-2 py-0.5 rounded bg-gray-200 text-gray-600">{entry.refType}</span>}
                {entry.isAutoGenerated && <span className="text-xs px-2 py-0.5 rounded bg-blue-50 text-blue-600">Auto</span>}
                {entry.isReversed && <span className="text-xs px-2 py-0.5 rounded bg-red-50 text-red-600">Reversed</span>}
              </div>
              <table className="w-full text-sm">
                <tbody>
                  {entry.lines.map((line, idx) => (
                    <tr key={idx} className="border-b last:border-0">
                      <td className="px-4 py-1.5 w-16 font-mono text-xs text-gray-400">{line.account.code}</td>
                      <td className="px-4 py-1.5 flex-1">
                        {line.debit > 0 ? (
                          <span className="font-medium">{line.account.name}</span>
                        ) : (
                          <span className="pl-8 text-gray-600">To {line.account.name}</span>
                        )}
                      </td>
                      <td className="px-4 py-1.5 text-xs text-gray-400">{line.costCenter || ''}</td>
                      <td className="px-4 py-1.5 text-right font-mono w-28">{fmtCurrency(line.debit)}</td>
                      <td className="px-4 py-1.5 text-right font-mono w-28">{fmtCurrency(line.credit)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ))}
          {data.entries.length === 0 && (
            <div className="text-center py-12 text-gray-400">
              No entries for {new Date(date).toLocaleDateString('en-IN', { weekday: 'long', day: '2-digit', month: 'long', year: 'numeric' })}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
