import React, { useState, useEffect, useCallback } from 'react';
import api from '../../services/api';

interface DayBookEntry {
  id: string;
  entryNo: number;
  date: string;
  narration: string;
  refType: string | null;
  isAutoGenerated: boolean;
  isReversed: boolean;
  lines: {
    account: { code: string; name: string };
    debit: number;
    credit: number;
    costCenter: string | null;
  }[];
}

interface DayBookData {
  date: string;
  entries: DayBookEntry[];
  count: number;
  totalDebit: number;
  totalCredit: number;
}

export default function DayBook() {
  const [date, setDate] = useState(new Date().toISOString().split('T')[0]);
  const [data, setData] = useState<DayBookData | null>(null);
  const [loading, setLoading] = useState(false);

  const fetchData = useCallback(async () => {
    try {
      setLoading(true);
      const res = await api.get<DayBookData>('/journal-entries/daybook', { params: { date } });
      setData(res.data);
    } catch (err) {
      console.error('Failed to fetch daybook:', err);
    } finally {
      setLoading(false);
    }
  }, [date]);

  useEffect(() => { fetchData(); }, [fetchData]);

  const fmtCurrency = (n: number): string => {
    if (n === 0) return '';
    return '\u20B9' + n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  };

  const moveDate = (days: number) => {
    const d = new Date(date);
    d.setDate(d.getDate() + days);
    setDate(d.toISOString().split('T')[0]);
  };

  const fmtDisplayDate = (d: string): string => new Date(d).toLocaleDateString('en-IN', { weekday: 'long', day: '2-digit', month: 'long', year: 'numeric' });

  return (
    <div className="min-h-screen bg-slate-50">
      <div className="p-3 md:p-6 space-y-0">
        {/* Page Toolbar */}
        <div className="bg-slate-800 text-white px-4 py-2.5 -mx-3 md:-mx-6 -mt-3 md:-mt-6 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <h1 className="text-sm font-bold tracking-wide uppercase">Day Book</h1>
            <span className="text-[10px] text-slate-400">|</span>
            <span className="text-[10px] text-slate-400">Daily journal entries register</span>
          </div>
        </div>

        {/* Date Navigation Toolbar */}
        <div className="bg-slate-100 border-x border-b border-slate-300 px-4 py-2 -mx-3 md:-mx-6 flex items-center gap-4 flex-wrap">
          <button
            onClick={() => moveDate(-1)}
            className="px-3 py-1 bg-white border border-slate-300 text-slate-600 text-[11px] font-medium hover:bg-slate-50"
          >
            Prev
          </button>
          <input
            type="date"
            value={date}
            onChange={e => setDate(e.target.value)}
            className="border border-slate-300 px-2.5 py-1.5 text-xs text-slate-700 bg-white focus:outline-none focus:ring-1 focus:ring-slate-400 focus:border-slate-400"
          />
          <button
            onClick={() => moveDate(1)}
            className="px-3 py-1 bg-white border border-slate-300 text-slate-600 text-[11px] font-medium hover:bg-slate-50"
          >
            Next
          </button>
          <button
            onClick={() => setDate(new Date().toISOString().split('T')[0])}
            className="px-3 py-1 bg-blue-600 text-white text-[11px] font-medium hover:bg-blue-700"
          >
            Today
          </button>
          <span className="text-[10px] text-slate-500 uppercase tracking-widest ml-auto">{fmtDisplayDate(date)}</span>
        </div>

        {/* KPI Summary Cards */}
        {data && (
          <div className="grid grid-cols-3 border-x border-b border-slate-300 -mx-3 md:-mx-6">
            <div className="bg-white px-4 py-3 border-r border-slate-300 border-l-4 border-l-blue-500">
              <div className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Entries</div>
              <div className="text-xl font-bold text-slate-800 mt-1 font-mono tabular-nums">{data.count}</div>
            </div>
            <div className="bg-white px-4 py-3 border-r border-slate-300 border-l-4 border-l-emerald-500">
              <div className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Total Debit</div>
              <div className="text-xl font-bold text-slate-800 mt-1 font-mono tabular-nums">{fmtCurrency(data.totalDebit) || '--'}</div>
            </div>
            <div className="bg-white px-4 py-3 border-l-4 border-l-amber-500">
              <div className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Total Credit</div>
              <div className="text-xl font-bold text-slate-800 mt-1 font-mono tabular-nums">{fmtCurrency(data.totalCredit) || '--'}</div>
            </div>
          </div>
        )}

        {/* Loading */}
        {loading && (
          <div className="text-center py-8">
            <div className="text-xs text-slate-400 uppercase tracking-widest">Loading...</div>
          </div>
        )}

        {/* Entries */}
        {data && !loading && (
          <div className="-mx-3 md:-mx-6">
            {data.entries.map(entry => (
              <div key={entry.id} className={`border-x border-b border-slate-300 overflow-hidden ${entry.isReversed ? 'opacity-50' : ''}`}>
                {/* Entry Header */}
                <div className="bg-slate-800 text-white px-4 py-2 flex items-center gap-3">
                  <span className="font-mono text-[10px] text-slate-400">#{entry.entryNo}</span>
                  <span className="text-xs font-medium flex-1">{entry.narration}</span>
                  {entry.refType && (
                    <span className="text-[9px] font-bold uppercase px-1.5 py-0.5 bg-slate-700 text-slate-300 border border-slate-600">
                      {entry.refType}
                    </span>
                  )}
                  {entry.isAutoGenerated && (
                    <span className="text-[9px] font-bold uppercase px-1.5 py-0.5 border border-blue-400/30 bg-blue-500/20 text-blue-200">Auto</span>
                  )}
                  {entry.isReversed && (
                    <span className="text-[9px] font-bold uppercase px-1.5 py-0.5 border border-red-400/30 bg-red-500/20 text-red-200">Reversed</span>
                  )}
                </div>
                {/* Entry Lines */}
                <table className="w-full text-xs">
                  <tbody>
                    {entry.lines.map((line, idx) => (
                      <tr key={idx} className="border-b border-slate-100 even:bg-slate-50/50">
                        <td className="px-3 py-1.5 w-16 font-mono text-[10px] text-slate-400 border-r border-slate-100">{line.account.code}</td>
                        <td className="px-3 py-1.5 flex-1 border-r border-slate-100">
                          {line.debit > 0 ? (
                            <span className="font-semibold text-slate-700">{line.account.name}</span>
                          ) : (
                            <span className="pl-8 text-slate-500">To {line.account.name}</span>
                          )}
                        </td>
                        <td className="px-3 py-1.5 text-[10px] text-slate-400 w-24 border-r border-slate-100">{line.costCenter || ''}</td>
                        <td className="px-3 py-1.5 text-right font-mono tabular-nums w-28 text-slate-700 border-r border-slate-100">{fmtCurrency(line.debit)}</td>
                        <td className="px-3 py-1.5 text-right font-mono tabular-nums w-28 text-slate-700">{fmtCurrency(line.credit)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ))}
            {data.entries.length === 0 && (
              <div className="text-center py-16 border-x border-b border-slate-300">
                <div className="text-xs text-slate-400 uppercase tracking-widest">No entries for {fmtDisplayDate(date)}</div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
