import React, { useState, useEffect, useCallback } from 'react';
import api from '../../services/api';

interface Account {
  id: string;
  code: string;
  name: string;
  type: string;
}

interface JournalLine {
  id: string;
  accountId: string;
  account: { code: string; name: string; type: string };
  debit: number;
  credit: number;
  narration: string | null;
  costCenter: string | null;
}

interface JournalEntryData {
  id: string;
  entryNo: number;
  date: string;
  narration: string;
  refType: string | null;
  isAutoGenerated: boolean;
  isReversed: boolean;
  userId: string;
  createdAt: string;
  lines: JournalLine[];
}

const COST_CENTERS = ['DISTILLERY', 'BOILER', 'DDGS', 'ADMIN', 'TRANSPORT', 'MAINTENANCE'];
const REF_TYPES = ['JOURNAL', 'SALE', 'PURCHASE', 'PAYMENT', 'RECEIPT', 'CONTRA'];

interface FormLine {
  accountId: string;
  debit: string;
  credit: string;
  narration: string;
  costCenter: string;
}

const emptyLine = (): FormLine => ({ accountId: '', debit: '', credit: '', narration: '', costCenter: '' });

export default function JournalEntry() {
  const [entries, setEntries] = useState<JournalEntryData[]>([]);
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [loading, setLoading] = useState(true);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(0);
  const [showForm, setShowForm] = useState(false);
  const [expandedEntry, setExpandedEntry] = useState<string | null>(null);
  const [dateFilter, setDateFilter] = useState({ from: '', to: '' });

  // Form state
  const [form, setForm] = useState({
    date: new Date().toISOString().split('T')[0],
    narration: '',
    refType: 'JOURNAL',
    lines: [emptyLine(), emptyLine()],
  });

  const fetchEntries = useCallback(async () => {
    try {
      setLoading(true);
      const params: Record<string, string> = { limit: '50', offset: String(page * 50) };
      if (dateFilter.from) params.from = dateFilter.from;
      if (dateFilter.to) params.to = dateFilter.to;
      const res = await api.get<{ entries: JournalEntryData[]; total: number }>('/journal-entries', { params });
      setEntries(res.data.entries);
      setTotal(res.data.total);
    } catch (err) {
      console.error('Failed to fetch journal entries:', err);
    } finally {
      setLoading(false);
    }
  }, [page, dateFilter]);

  const fetchAccounts = useCallback(async () => {
    try {
      const res = await api.get<Account[]>('/chart-of-accounts');
      setAccounts(res.data);
    } catch (err) {
      console.error('Failed to fetch accounts:', err);
    }
  }, []);

  useEffect(() => { fetchEntries(); }, [fetchEntries]);
  useEffect(() => { fetchAccounts(); }, [fetchAccounts]);

  const totalDebit = form.lines.reduce((s, l) => s + (parseFloat(l.debit) || 0), 0);
  const totalCredit = form.lines.reduce((s, l) => s + (parseFloat(l.credit) || 0), 0);
  const difference = Math.abs(totalDebit - totalCredit);
  const isBalanced = difference < 0.01;

  const handleAddLine = () => {
    setForm(f => ({ ...f, lines: [...f.lines, emptyLine()] }));
  };

  const handleRemoveLine = (idx: number) => {
    if (form.lines.length <= 2) return;
    setForm(f => ({ ...f, lines: f.lines.filter((_, i) => i !== idx) }));
  };

  const updateLine = (idx: number, field: keyof FormLine, value: string) => {
    setForm(f => ({
      ...f,
      lines: f.lines.map((l, i) => i === idx ? { ...l, [field]: value } : l),
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!isBalanced) { alert('Debits must equal Credits!'); return; }

    try {
      const payload = {
        date: form.date,
        narration: form.narration,
        refType: form.refType || 'JOURNAL',
        lines: form.lines
          .filter(l => l.accountId && (parseFloat(l.debit) > 0 || parseFloat(l.credit) > 0))
          .map(l => ({
            accountId: l.accountId,
            debit: parseFloat(l.debit) || 0,
            credit: parseFloat(l.credit) || 0,
            narration: l.narration || null,
            costCenter: l.costCenter || null,
          })),
      };

      if (payload.lines.length < 2) { alert('At least 2 lines required (double entry)'); return; }

      await api.post('/journal-entries', payload);
      setShowForm(false);
      setForm({ date: new Date().toISOString().split('T')[0], narration: '', refType: 'JOURNAL', lines: [emptyLine(), emptyLine()] });
      await fetchEntries();
    } catch (err: unknown) {
      const msg = (err as { response?: { data?: { error?: string } } })?.response?.data?.error || 'Save failed';
      alert(msg);
    }
  };

  const handleReverse = async (id: string) => {
    if (!confirm('Reverse this journal entry? A new opposite entry will be created.')) return;
    try {
      await api.post(`/api/journal-entries/${id}/reverse`);
      await fetchEntries();
    } catch (err: unknown) {
      const msg = (err as { response?: { data?: { error?: string } } })?.response?.data?.error || 'Reversal failed';
      alert(msg);
    }
  };

  const fmtCurrency = (n: number): string => {
    if (n === 0) return '';
    return '\u20B9' + n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  };

  const fmtDate = (d: string): string => new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });

  if (loading && entries.length === 0) return (
    <div className="min-h-screen bg-slate-50 flex items-center justify-center">
      <div className="text-xs text-slate-400 uppercase tracking-widest">Loading...</div>
    </div>
  );

  return (
    <div className="min-h-screen bg-slate-50">
      <div className="p-3 md:p-6 space-y-0">
        {/* Page Toolbar */}
        <div className="bg-slate-800 text-white px-4 py-2.5 -mx-3 md:-mx-6 -mt-3 md:-mt-6 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <h1 className="text-sm font-bold tracking-wide uppercase">Journal Entries</h1>
            <span className="text-[10px] text-slate-400">|</span>
            <span className="text-[10px] text-slate-400">Double-entry bookkeeping ledger transactions</span>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => setShowForm(true)}
              className="px-3 py-1 bg-blue-600 text-white text-[11px] font-medium hover:bg-blue-700"
            >
              + New Entry
            </button>
          </div>
        </div>

        {/* Filter Toolbar */}
        <div className="bg-slate-100 border-x border-b border-slate-300 px-4 py-2 -mx-3 md:-mx-6 flex items-center gap-4 flex-wrap">
          <div>
            <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-0.5">From</label>
            <input
              type="date"
              value={dateFilter.from}
              onChange={e => setDateFilter(f => ({ ...f, from: e.target.value }))}
              className="border border-slate-300 px-2.5 py-1.5 text-xs text-slate-700 bg-white focus:outline-none focus:ring-1 focus:ring-slate-400 focus:border-slate-400"
            />
          </div>
          <div>
            <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-0.5">To</label>
            <input
              type="date"
              value={dateFilter.to}
              onChange={e => setDateFilter(f => ({ ...f, to: e.target.value }))}
              className="border border-slate-300 px-2.5 py-1.5 text-xs text-slate-700 bg-white focus:outline-none focus:ring-1 focus:ring-slate-400 focus:border-slate-400"
            />
          </div>
          <div className="flex items-end h-full">
            <span className="text-[10px] text-slate-400 uppercase tracking-widest pb-2">{total} entries found</span>
          </div>
        </div>

        {/* Entries Table */}
        <div className="border-x border-b border-slate-300 -mx-3 md:-mx-6 overflow-hidden">
          <table className="w-full text-xs">
            <thead>
              <tr className="bg-slate-800 text-white">
                <th className="text-left px-3 py-2 font-semibold text-[10px] uppercase tracking-widest border-r border-slate-700 w-16">No.</th>
                <th className="text-left px-3 py-2 font-semibold text-[10px] uppercase tracking-widest border-r border-slate-700 w-28">Date</th>
                <th className="text-left px-3 py-2 font-semibold text-[10px] uppercase tracking-widest border-r border-slate-700">Narration</th>
                <th className="text-left px-3 py-2 font-semibold text-[10px] uppercase tracking-widest border-r border-slate-700 w-24">Type</th>
                <th className="text-left px-3 py-2 font-semibold text-[10px] uppercase tracking-widest border-r border-slate-700 w-20">Status</th>
                <th className="text-right px-3 py-2 font-semibold text-[10px] uppercase tracking-widest border-r border-slate-700 w-32">Amount</th>
                <th className="text-center px-3 py-2 font-semibold text-[10px] uppercase tracking-widest w-10"></th>
              </tr>
            </thead>
            <tbody>
              {entries.map(entry => (
                <React.Fragment key={entry.id}>
                  <tr
                    className={`hover:bg-blue-50 cursor-pointer border-b border-slate-100 ${entry.isReversed ? 'opacity-50' : ''} ${expandedEntry === entry.id ? 'bg-blue-50' : 'even:bg-slate-50/50'}`}
                    onClick={() => setExpandedEntry(expandedEntry === entry.id ? null : entry.id)}
                  >
                    <td className="px-3 py-1.5 font-mono text-[10px] text-slate-400 border-r border-slate-100">#{entry.entryNo}</td>
                    <td className="px-3 py-1.5 text-slate-600 text-[11px] border-r border-slate-100">{fmtDate(entry.date)}</td>
                    <td className="px-3 py-1.5 text-slate-700 font-medium border-r border-slate-100">{entry.narration}</td>
                    <td className="px-3 py-1.5 border-r border-slate-100">
                      {entry.refType && (
                        <span className="text-[9px] font-bold uppercase px-1.5 py-0.5 border border-slate-300 bg-slate-50 text-slate-600">
                          {entry.refType}
                        </span>
                      )}
                    </td>
                    <td className="px-3 py-1.5 border-r border-slate-100">
                      <div className="flex gap-1">
                        {entry.isAutoGenerated && (
                          <span className="text-[9px] font-bold uppercase px-1.5 py-0.5 border border-blue-300 bg-blue-50 text-blue-700">Auto</span>
                        )}
                        {entry.isReversed && (
                          <span className="text-[9px] font-bold uppercase px-1.5 py-0.5 border border-red-300 bg-red-50 text-red-700">Reversed</span>
                        )}
                      </div>
                    </td>
                    <td className="px-3 py-1.5 text-right font-mono tabular-nums text-slate-700 border-r border-slate-100">
                      {fmtCurrency(entry.lines.reduce((s, l) => s + l.debit, 0))}
                    </td>
                    <td className="px-3 py-1.5 text-center text-slate-400 text-[10px]">
                      {expandedEntry === entry.id ? '\u25B2' : '\u25BC'}
                    </td>
                  </tr>

                  {/* Expanded Detail */}
                  {expandedEntry === entry.id && (
                    <tr>
                      <td colSpan={7} className="p-0">
                        <div className="bg-slate-50 border-t border-slate-200 px-6 py-4">
                          <table className="w-full text-xs">
                            <thead>
                              <tr className="bg-slate-800 text-white">
                                <th className="text-left px-3 py-2 font-semibold text-[10px] uppercase tracking-widest border-r border-slate-700">Account</th>
                                <th className="text-left px-3 py-2 font-semibold text-[10px] uppercase tracking-widest border-r border-slate-700">Narration</th>
                                <th className="text-left px-3 py-2 font-semibold text-[10px] uppercase tracking-widest border-r border-slate-700">Cost Center</th>
                                <th className="text-right px-3 py-2 font-semibold text-[10px] uppercase tracking-widest border-r border-slate-700">Debit</th>
                                <th className="text-right px-3 py-2 font-semibold text-[10px] uppercase tracking-widest">Credit</th>
                              </tr>
                            </thead>
                            <tbody>
                              {entry.lines.map(line => (
                                <tr key={line.id} className="border-b border-slate-100">
                                  <td className="px-3 py-1.5 text-slate-700 border-r border-slate-100">
                                    <span className="font-mono text-[10px] text-slate-400 mr-1.5">{line.account.code}</span>
                                    {line.account.name}
                                  </td>
                                  <td className="px-3 py-1.5 text-slate-500 text-[11px] border-r border-slate-100">{line.narration || '--'}</td>
                                  <td className="px-3 py-1.5 text-slate-500 text-[11px] border-r border-slate-100">{line.costCenter || '--'}</td>
                                  <td className="px-3 py-1.5 text-right font-mono tabular-nums text-slate-700 border-r border-slate-100">{fmtCurrency(line.debit)}</td>
                                  <td className="px-3 py-1.5 text-right font-mono tabular-nums text-slate-700">{fmtCurrency(line.credit)}</td>
                                </tr>
                              ))}
                            </tbody>
                            <tfoot>
                              <tr className="bg-slate-800 text-white font-semibold">
                                <td colSpan={3} className="px-3 py-2 text-right text-[10px] uppercase tracking-widest">Total</td>
                                <td className="px-3 py-2 text-right font-mono tabular-nums border-r border-slate-700">{fmtCurrency(entry.lines.reduce((s, l) => s + l.debit, 0))}</td>
                                <td className="px-3 py-2 text-right font-mono tabular-nums">{fmtCurrency(entry.lines.reduce((s, l) => s + l.credit, 0))}</td>
                              </tr>
                            </tfoot>
                          </table>
                          {!entry.isReversed && !entry.isAutoGenerated && (
                            <div className="mt-3 flex justify-end">
                              <button
                                onClick={(e) => { e.stopPropagation(); handleReverse(entry.id); }}
                                className="px-3 py-1 bg-white border border-red-300 text-red-600 text-[11px] font-medium hover:bg-red-50"
                              >
                                Reverse Entry
                              </button>
                            </div>
                          )}
                        </div>
                      </td>
                    </tr>
                  )}
                </React.Fragment>
              ))}
              {entries.length === 0 && (
                <tr>
                  <td colSpan={7}>
                    <div className="text-center py-16">
                      <div className="text-xs text-slate-400 uppercase tracking-widest">No journal entries found</div>
                    </div>
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>

        {/* Pagination */}
        {total > 50 && (
          <div className="flex items-center justify-between px-4 py-2 bg-slate-100 border-x border-b border-slate-300 -mx-3 md:-mx-6">
            <span className="text-[10px] text-slate-500 uppercase tracking-widest">Showing {Math.min(entries.length, 50)} of {total}</span>
            <div className="flex gap-1">
              <button
                onClick={() => setPage(p => Math.max(0, p - 1))}
                disabled={page === 0}
                className="px-3 py-1 text-[11px] border border-slate-300 hover:bg-slate-50 disabled:opacity-40"
              >
                Prev
              </button>
              <span className="px-3 py-1 text-[11px] text-slate-600">Page {page + 1} of {Math.ceil(total / 50)}</span>
              <button
                onClick={() => setPage(p => p + 1)}
                disabled={(page + 1) * 50 >= total}
                className="px-3 py-1 text-[11px] border border-slate-300 hover:bg-slate-50 disabled:opacity-40"
              >
                Next
              </button>
            </div>
          </div>
        )}

        {/* New Entry Form Modal */}
        {showForm && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 overflow-y-auto py-8">
            <div className="bg-white shadow-xl w-full max-w-3xl">
              <div className="bg-slate-800 text-white px-5 py-3">
                <h2 className="text-sm font-bold uppercase tracking-wide">New Journal Entry</h2>
              </div>
              <form onSubmit={handleSubmit} className="p-5 space-y-4">
                <div className="grid grid-cols-3 gap-3">
                  <div>
                    <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-0.5">Date</label>
                    <input
                      type="date"
                      value={form.date}
                      onChange={e => setForm(f => ({ ...f, date: e.target.value }))}
                      className="w-full border border-slate-300 px-2.5 py-1.5 text-xs text-slate-700 bg-white focus:outline-none focus:ring-1 focus:ring-slate-400 focus:border-slate-400"
                      required
                    />
                  </div>
                  <div>
                    <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-0.5">Type</label>
                    <select
                      value={form.refType}
                      onChange={e => setForm(f => ({ ...f, refType: e.target.value }))}
                      className="w-full border border-slate-300 px-2.5 py-1.5 text-xs text-slate-700 bg-white focus:outline-none focus:ring-1 focus:ring-slate-400 focus:border-slate-400"
                    >
                      {REF_TYPES.map(t => <option key={t} value={t}>{t}</option>)}
                    </select>
                  </div>
                  <div>
                    <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-0.5">Narration</label>
                    <input
                      value={form.narration}
                      onChange={e => setForm(f => ({ ...f, narration: e.target.value }))}
                      className="w-full border border-slate-300 px-2.5 py-1.5 text-xs text-slate-700 bg-white focus:outline-none focus:ring-1 focus:ring-slate-400 focus:border-slate-400"
                      placeholder="e.g. Office rent for March 2026"
                      required
                    />
                  </div>
                </div>

                {/* Lines Table */}
                <div className="border border-slate-300 overflow-hidden">
                  <table className="w-full text-xs">
                    <thead>
                      <tr className="bg-slate-800 text-white">
                        <th className="text-left px-3 py-2 font-semibold text-[10px] uppercase tracking-widest border-r border-slate-700">Account</th>
                        <th className="text-left px-3 py-2 font-semibold text-[10px] uppercase tracking-widest border-r border-slate-700 w-28">Debit</th>
                        <th className="text-left px-3 py-2 font-semibold text-[10px] uppercase tracking-widest border-r border-slate-700 w-28">Credit</th>
                        <th className="text-left px-3 py-2 font-semibold text-[10px] uppercase tracking-widest border-r border-slate-700 w-32">Cost Center</th>
                        <th className="w-8"></th>
                      </tr>
                    </thead>
                    <tbody>
                      {form.lines.map((line, idx) => (
                        <tr key={idx} className="even:bg-slate-50/50 border-b border-slate-100">
                          <td className="px-3 py-1.5 border-r border-slate-100">
                            <select
                              value={line.accountId}
                              onChange={e => updateLine(idx, 'accountId', e.target.value)}
                              className="w-full border border-slate-300 px-2 py-1.5 text-xs text-slate-700 bg-white focus:outline-none focus:ring-1 focus:ring-slate-400 focus:border-slate-400"
                              required
                            >
                              <option value="">Select Account</option>
                              {accounts.map(a => (
                                <option key={a.id} value={a.id}>{a.code} -- {a.name}</option>
                              ))}
                            </select>
                          </td>
                          <td className="px-3 py-1.5 border-r border-slate-100">
                            <input
                              type="number"
                              step="0.01"
                              min="0"
                              value={line.debit}
                              onChange={e => {
                                updateLine(idx, 'debit', e.target.value);
                                if (parseFloat(e.target.value) > 0) updateLine(idx, 'credit', '');
                              }}
                              className="w-full border border-slate-300 px-2 py-1.5 text-xs text-right text-slate-700 bg-white focus:outline-none focus:ring-1 focus:ring-slate-400 focus:border-slate-400 font-mono tabular-nums"
                              placeholder="0.00"
                            />
                          </td>
                          <td className="px-3 py-1.5 border-r border-slate-100">
                            <input
                              type="number"
                              step="0.01"
                              min="0"
                              value={line.credit}
                              onChange={e => {
                                updateLine(idx, 'credit', e.target.value);
                                if (parseFloat(e.target.value) > 0) updateLine(idx, 'debit', '');
                              }}
                              className="w-full border border-slate-300 px-2 py-1.5 text-xs text-right text-slate-700 bg-white focus:outline-none focus:ring-1 focus:ring-slate-400 focus:border-slate-400 font-mono tabular-nums"
                              placeholder="0.00"
                            />
                          </td>
                          <td className="px-3 py-1.5 border-r border-slate-100">
                            <select
                              value={line.costCenter}
                              onChange={e => updateLine(idx, 'costCenter', e.target.value)}
                              className="w-full border border-slate-300 px-2 py-1.5 text-xs text-slate-700 bg-white focus:outline-none focus:ring-1 focus:ring-slate-400 focus:border-slate-400"
                            >
                              <option value="">--</option>
                              {COST_CENTERS.map(cc => <option key={cc} value={cc}>{cc}</option>)}
                            </select>
                          </td>
                          <td className="px-1">
                            {form.lines.length > 2 && (
                              <button type="button" onClick={() => handleRemoveLine(idx)} className="text-red-400 hover:text-red-600 text-xs font-bold">x</button>
                            )}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                    <tfoot>
                      <tr className="bg-slate-800 text-white font-semibold">
                        <td className="px-3 py-2 text-right text-[10px] uppercase tracking-widest border-r border-slate-700">Total</td>
                        <td className="px-3 py-2 text-right font-mono tabular-nums text-xs border-r border-slate-700">{fmtCurrency(totalDebit)}</td>
                        <td className="px-3 py-2 text-right font-mono tabular-nums text-xs border-r border-slate-700">{fmtCurrency(totalCredit)}</td>
                        <td colSpan={2} className="px-3 py-2">
                          {!isBalanced && difference > 0 && (
                            <span className="text-[10px] text-red-300 font-medium">Diff: {'\u20B9'}{difference.toFixed(2)}</span>
                          )}
                          {isBalanced && totalDebit > 0 && (
                            <span className="text-[10px] text-emerald-300 font-medium">Balanced</span>
                          )}
                        </td>
                      </tr>
                    </tfoot>
                  </table>
                </div>

                <button type="button" onClick={handleAddLine} className="px-3 py-1 bg-white border border-slate-300 text-slate-600 text-[11px] font-medium hover:bg-slate-50">
                  + Add Line
                </button>
              </form>
              <div className="bg-slate-100 border-t border-slate-300 px-5 py-3 flex justify-end gap-2">
                <button
                  type="button"
                  onClick={() => setShowForm(false)}
                  className="px-4 py-1 text-[11px] text-slate-600 hover:bg-slate-200"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={() => {
                    const formEl = document.querySelector('form');
                    if (formEl) formEl.requestSubmit();
                  }}
                  disabled={!isBalanced || totalDebit === 0}
                  className="px-4 py-1 bg-blue-600 text-white text-[11px] font-medium hover:bg-blue-700 disabled:opacity-50"
                >
                  Save Entry
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
