import React, { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import api from '../../services/api';
import { ComboAccount } from '../../components/accounts/AccountCombobox';
import NewJournalEntryModal from '../../components/accounts/NewJournalEntryModal';
import { useHotkeys } from '../../hooks/useHotkeys';
import { Division, DIVISION_COLORS } from '../../constants/divisions';
import {
  PageToolbar, TipBanner, FilterBar, SecondaryFilterBar, FilterLabel,
  PresetButtons, DateRangeInputs, DivisionSegmented, KpiStrip, KpiTile,
  DivisionSplitBar, HelpModal, TableContainer, Th, RefTypeChips,
  RefType, DivisionFilter, computePreset, fmtINR, fmtDate,
} from '../../components/accounts/BooksShell';

interface JELine {
  id: string;
  accountId: string;
  account: { code: string; name: string; type: string };
  debit: number;
  credit: number;
  narration: string | null;
  costCenter: string | null;
  division: string | null;
}

interface JE {
  id: string;
  entryNo: number;
  date: string;
  narration: string;
  refType: string | null;
  refId: string | null;
  isAutoGenerated: boolean;
  isReversed: boolean;
  userId: string;
  createdAt: string;
  lines: JELine[];
}

const PAGE_SIZE = 50;

export default function JournalEntry() {
  const [accounts, setAccounts] = useState<ComboAccount[]>([]);
  const [entries, setEntries] = useState<JE[]>([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(false);
  const [page, setPage] = useState(0);

  const [dateRange, setDateRange] = useState({ from: '', to: '' });
  const [divisionFilter, setDivisionFilter] = useState<DivisionFilter>('ALL');
  const [narrationSearch, setNarrationSearch] = useState('');
  const [refTypeFilter, setRefTypeFilter] = useState<Set<RefType>>(new Set());
  const [amtFrom, setAmtFrom] = useState('');
  const [amtTo, setAmtTo] = useState('');
  const [expanded, setExpanded] = useState<Set<string>>(new Set());

  const [newEntryOpen, setNewEntryOpen] = useState(false);
  const [showHelp, setShowHelp] = useState(false);
  const narrationRef = useRef<HTMLInputElement>(null);

  const fetchAccounts = useCallback(async () => {
    try {
      const res = await api.get<ComboAccount[]>('/chart-of-accounts');
      setAccounts(res.data);
    } catch (err) { console.error(err); }
  }, []);
  useEffect(() => { fetchAccounts(); }, [fetchAccounts]);

  const fetchEntries = useCallback(async () => {
    try {
      setLoading(true);
      const params: Record<string, string> = {
        limit: String(PAGE_SIZE),
        offset: String(page * PAGE_SIZE),
      };
      if (dateRange.from) params.from = dateRange.from;
      if (dateRange.to) params.to = dateRange.to;
      if (divisionFilter !== 'ALL') params.division = divisionFilter;
      // Only send single ref type to server if exactly one chip picked; otherwise client-filter
      if (refTypeFilter.size === 1) params.refType = Array.from(refTypeFilter)[0];
      const res = await api.get<{ entries: JE[]; total: number }>('/journal-entries', { params });
      setEntries(res.data.entries);
      setTotal(res.data.total);
    } catch (err) { console.error('Failed to fetch journal entries:', err); }
    finally { setLoading(false); }
  }, [page, dateRange, divisionFilter, refTypeFilter]);
  useEffect(() => { fetchEntries(); }, [fetchEntries]);

  // Filter-change wrappers — reset page to 0 inline instead of via a separate
  // effect, otherwise we trigger a double-fetch (first with old page + new
  // filters, then with page 0 + new filters) and risk a response race.
  const applyDateRange = useCallback((r: { from: string; to: string }) => {
    setDateRange(r);
    setPage(0);
  }, []);
  const applyDivision = useCallback((d: DivisionFilter) => {
    setDivisionFilter(d);
    setPage(0);
  }, []);

  const filtered = useMemo(() => {
    const nq = narrationSearch.trim().toLowerCase();
    const af = amtFrom ? parseFloat(amtFrom) : null;
    const at = amtTo ? parseFloat(amtTo) : null;
    const out = entries.filter(e => {
      if (nq && !e.narration.toLowerCase().includes(nq)) return false;
      if (refTypeFilter.size > 1 && (!e.refType || !refTypeFilter.has(e.refType as RefType))) return false;
      if (af !== null || at !== null) {
        const dTotal = e.lines.reduce((s, l) => s + l.debit, 0);
        if (af !== null && dTotal < af) return false;
        if (at !== null && dTotal > at) return false;
      }
      return true;
    });
    const totalDebit = out.reduce((s, e) => s + e.lines.reduce((ls, l) => ls + l.debit, 0), 0);
    const totalCredit = out.reduce((s, e) => s + e.lines.reduce((ls, l) => ls + l.credit, 0), 0);
    return { entries: out, totalDebit, totalCredit };
  }, [entries, narrationSearch, refTypeFilter, amtFrom, amtTo]);

  const flatLines = useMemo(
    () => filtered.entries.flatMap(e => e.lines.map(l => ({ division: l.division, debit: l.debit, credit: l.credit }))),
    [filtered.entries]
  );

  const clearAllFilters = useCallback(() => {
    setNarrationSearch(''); setRefTypeFilter(new Set()); setAmtFrom(''); setAmtTo('');
  }, []);

  const toggleExpand = (id: string) => setExpanded(s => { const n = new Set(s); if (n.has(id)) n.delete(id); else n.add(id); return n; });

  const handleReverse = async (id: string) => {
    if (!confirm('Reverse this journal entry? A new opposite entry will be created.')) return;
    try {
      await api.post(`/journal-entries/${id}/reverse`);
      await fetchEntries();
    } catch (err: unknown) {
      const msg = (err as { response?: { data?: { error?: string } } })?.response?.data?.error || 'Reversal failed';
      alert(msg);
    }
  };

  useHotkeys([
    { key: 'f', ctrl: true, handler: e => { e.preventDefault(); narrationRef.current?.focus(); } },
    { key: 'n', handler: e => { e.preventDefault(); setNewEntryOpen(true); } },
    { key: 't', handler: e => { e.preventDefault(); applyDateRange(computePreset('today')); } },
    { key: 'm', handler: e => { e.preventDefault(); applyDateRange(computePreset('month')); } },
    { key: '0', handler: e => { e.preventDefault(); applyDivision('ALL'); } },
    { key: '1', handler: e => { e.preventDefault(); applyDivision('SUGAR'); } },
    { key: '2', handler: e => { e.preventDefault(); applyDivision('POWER'); } },
    { key: '3', handler: e => { e.preventDefault(); applyDivision('ETHANOL'); } },
    { key: '?', shift: true, handler: e => { e.preventDefault(); setShowHelp(h => !h); } },
    { key: 'Escape', allowInInputs: true, handler: () => {
      if (showHelp) { setShowHelp(false); return; }
      if (newEntryOpen) return;
      clearAllFilters();
    } },
  ]);

  const toggleRefType = (rt: RefType) => {
    setRefTypeFilter(s => {
      const n = new Set(s); if (n.has(rt)) n.delete(rt); else n.add(rt); return n;
    });
    setPage(0);
  };

  const net = filtered.totalDebit - filtered.totalCredit;
  const balanced = Math.abs(net) < 0.01;
  const pageCount = Math.max(1, Math.ceil(total / PAGE_SIZE));

  return (
    <div className="min-h-screen bg-slate-50">
      <div className="p-3 md:p-6 space-y-0">
        <PageToolbar
          title="Journal Entries"
          subtitle="Double-entry ledger · keyboard-first · expandable lines"
          statusBadge={entries.length > 0 && (
            <span className={`text-[9px] font-bold uppercase px-1.5 py-0.5 border ${balanced ? 'border-emerald-400/50 bg-emerald-500/20 text-emerald-200' : 'border-red-400/50 bg-red-500/20 text-red-200'}`}>
              {balanced ? 'Balanced' : 'Out of Balance'}
            </span>
          )}
        >
          <button onClick={() => setNewEntryOpen(true)} className="px-3 py-1 bg-blue-600 text-white text-[11px] font-medium hover:bg-blue-700" title="Post a new journal entry (N)">+ New Entry (N)</button>
          <button onClick={() => setShowHelp(true)} className="w-6 h-6 border border-slate-600 text-slate-300 text-xs font-bold hover:bg-slate-700" title="Keyboard shortcuts (?)">?</button>
        </PageToolbar>

        <TipBanner storageKey="je_tip_dismissed">
          Tip: <kbd className="px-1 bg-white border border-amber-300 font-mono">Ctrl+F</kbd> to search narration,
          <kbd className="ml-1 px-1 bg-white border border-amber-300 font-mono">N</kbd> for new entry,
          click any row to expand its lines.
        </TipBanner>

        <div className="-mx-3 md:-mx-6 border-x border-b border-blue-200 bg-blue-50 px-4 py-2 text-[11px] text-slate-700 flex items-center gap-3">
          <span className="font-bold uppercase tracking-widest text-blue-700">📘 Journal vs Ledger</span>
          <span><strong>Journal</strong> (this page) = the chronological book — each transaction with both Dr and Cr lines, posted on a date. <strong>Ledger</strong> (<a href="/accounts/ledger" className="text-blue-700 underline">/accounts/ledger</a>) = the per-account view — pick one account and see its running balance, with each Journal Entry as a row.</span>
        </div>

        <FilterBar>
          <PresetButtons onPreset={p => applyDateRange(computePreset(p))} />
          <DateRangeInputs from={dateRange.from} to={dateRange.to} onChange={applyDateRange} />
          <DivisionSegmented value={divisionFilter} onChange={applyDivision} />
        </FilterBar>

        <SecondaryFilterBar>
          <div className="flex-1 min-w-[200px]">
            <FilterLabel>Narration (Ctrl+F)</FilterLabel>
            <input ref={narrationRef} type="text" value={narrationSearch} onChange={e => setNarrationSearch(e.target.value)}
              placeholder="Search narration…"
              className="w-full border border-slate-300 px-2.5 py-1.5 text-xs focus:outline-none focus:ring-1 focus:ring-slate-400" />
          </div>
          <RefTypeChips value={refTypeFilter} onToggle={toggleRefType} />
          <div>
            <FilterLabel>Amt From</FilterLabel>
            <input type="number" value={amtFrom} onChange={e => setAmtFrom(e.target.value)} className="w-24 border border-slate-300 px-2 py-1.5 text-xs font-mono focus:outline-none focus:ring-1 focus:ring-slate-400" />
          </div>
          <div>
            <FilterLabel>Amt To</FilterLabel>
            <input type="number" value={amtTo} onChange={e => setAmtTo(e.target.value)} className="w-24 border border-slate-300 px-2 py-1.5 text-xs font-mono focus:outline-none focus:ring-1 focus:ring-slate-400" />
          </div>
        </SecondaryFilterBar>

        {loading && <div className="text-xs text-slate-400 uppercase tracking-widest py-4 px-4">Loading entries...</div>}

        {!loading && (
          <>
            <KpiStrip cols={5}>
              <KpiTile label="Entries (page)" value={filtered.entries.length} sub={`Total: ${total.toLocaleString('en-IN')}`} color="slate" />
              <KpiTile label="Total Debit" value={fmtINR(filtered.totalDebit) || '\u20B90.00'} color="emerald" valueClass="text-emerald-700" />
              <KpiTile label="Total Credit" value={fmtINR(filtered.totalCredit) || '\u20B90.00'} color="rose" valueClass="text-rose-700" />
              <KpiTile label="Net (should be 0)" value={net < 0 ? '-' + fmtINR(Math.abs(net)) : fmtINR(net) || '\u20B90.00'} color="amber" valueClass={balanced ? 'text-slate-800' : 'text-red-700'} />
              <KpiTile label="Auto-Generated" value={filtered.entries.filter(e => e.isAutoGenerated).length} sub="system entries" color="indigo" last />
            </KpiStrip>

            <DivisionSplitBar lines={flatLines} />

            <TableContainer>
              <table className="w-full text-xs">
                <thead>
                  <tr className="bg-slate-800 text-white">
                    <Th>Date</Th>
                    <Th>Entry #</Th>
                    <Th>Narration</Th>
                    <Th>Ref</Th>
                    <Th>Flags</Th>
                    <Th align="right">Debit</Th>
                    <Th align="right">Credit</Th>
                    <Th align="right" last>Actions</Th>
                  </tr>
                </thead>
                <tbody>
                  {filtered.entries.map((e, i) => {
                    const dTotal = e.lines.reduce((s, l) => s + l.debit, 0);
                    const cTotal = e.lines.reduce((s, l) => s + l.credit, 0);
                    const isOpen = expanded.has(e.id);
                    return (
                      <React.Fragment key={e.id}>
                        <tr className={`hover:bg-blue-50 border-b border-slate-100 ${i % 2 ? 'bg-slate-50/50' : ''} ${e.isReversed ? 'opacity-50' : ''}`}>
                          <td onClick={() => toggleExpand(e.id)} className="px-3 py-1.5 text-slate-600 border-r border-slate-100 cursor-pointer">{fmtDate(e.date)}</td>
                          <td onClick={() => toggleExpand(e.id)} className="px-3 py-1.5 font-mono text-[10px] text-slate-500 border-r border-slate-100 cursor-pointer">
                            <span className="mr-1 text-slate-400">{isOpen ? '▾' : '▸'}</span>#{e.entryNo}
                          </td>
                          <td onClick={() => toggleExpand(e.id)} className="px-3 py-1.5 text-slate-700 border-r border-slate-100 cursor-pointer">{e.narration}</td>
                          <td className="px-3 py-1.5 text-[10px] text-slate-500 border-r border-slate-100">{e.refType || '--'}</td>
                          <td className="px-3 py-1.5 text-[10px] border-r border-slate-100">
                            {e.isAutoGenerated && <span className="text-[9px] font-bold uppercase px-1 py-0.5 border border-indigo-300 bg-indigo-50 text-indigo-700 mr-1">AUTO</span>}
                            {e.isReversed && <span className="text-[9px] font-bold uppercase px-1 py-0.5 border border-red-300 bg-red-50 text-red-700">REV</span>}
                          </td>
                          <td className="px-3 py-1.5 text-right font-mono tabular-nums text-slate-700 border-r border-slate-100">{fmtINR(dTotal)}</td>
                          <td className="px-3 py-1.5 text-right font-mono tabular-nums text-slate-700 border-r border-slate-100">{fmtINR(cTotal)}</td>
                          <td className="px-3 py-1.5 text-right">
                            {!e.isReversed && !e.isAutoGenerated && (
                              <button
                                onClick={() => handleReverse(e.id)}
                                className="text-[10px] font-bold uppercase px-2 py-0.5 border border-red-300 text-red-700 hover:bg-red-50"
                              >Reverse</button>
                            )}
                          </td>
                        </tr>
                        {isOpen && e.lines.map((l, li) => (
                          <tr key={`${e.id}-${li}`} className="bg-slate-50/80 border-b border-slate-100 text-[11px]">
                            <td colSpan={2}></td>
                            <td className="px-3 py-1 pl-8 text-slate-600 border-r border-slate-100">
                              <span className="font-mono text-[10px] text-slate-400">{l.account.code}</span> · {l.account.name}
                              {l.narration && <span className="text-[10px] text-slate-400 ml-2">({l.narration})</span>}
                              {l.costCenter && <span className="text-[10px] text-slate-400 ml-2">[{l.costCenter}]</span>}
                            </td>
                            <td className="px-3 py-1 border-r border-slate-100"></td>
                            <td className="px-3 py-1 text-[10px] border-r border-slate-100">
                              {l.division && (
                                <span className={`inline-block w-2 h-2 mr-1 align-middle ${DIVISION_COLORS[l.division as Division] || 'bg-slate-300'}`}></span>
                              )}
                              <span className="text-slate-500">{l.division || '--'}</span>
                            </td>
                            <td className="px-3 py-1 text-right font-mono tabular-nums text-emerald-700 border-r border-slate-100">{fmtINR(l.debit)}</td>
                            <td className="px-3 py-1 text-right font-mono tabular-nums text-rose-700 border-r border-slate-100">{fmtINR(l.credit)}</td>
                            <td></td>
                          </tr>
                        ))}
                      </React.Fragment>
                    );
                  })}
                  {filtered.entries.length === 0 && (
                    <tr><td colSpan={8} className="text-center py-8 text-xs text-slate-400 uppercase tracking-widest">No journal entries match filters</td></tr>
                  )}
                </tbody>
                <tfoot>
                  <tr className="bg-slate-800 text-white font-semibold">
                    <td colSpan={5} className="px-3 py-2 text-right text-[10px] uppercase tracking-widest border-r border-slate-700">Totals</td>
                    <td className="px-3 py-2 text-right font-mono tabular-nums border-r border-slate-700">{fmtINR(filtered.totalDebit)}</td>
                    <td className="px-3 py-2 text-right font-mono tabular-nums border-r border-slate-700">{fmtINR(filtered.totalCredit)}</td>
                    <td></td>
                  </tr>
                </tfoot>
              </table>
            </TableContainer>

            {pageCount > 1 && (
              <div className="bg-white border-x border-b border-slate-300 -mx-3 md:-mx-6 px-4 py-2 flex items-center justify-between">
                <div className="text-[10px] text-slate-500 uppercase tracking-widest">
                  Page {page + 1} of {pageCount} · Showing {page * PAGE_SIZE + 1}–{Math.min((page + 1) * PAGE_SIZE, total)} of {total.toLocaleString('en-IN')}
                </div>
                <div className="flex gap-1">
                  <button onClick={() => setPage(p => Math.max(0, p - 1))} disabled={page === 0}
                    className="px-3 py-1 bg-white border border-slate-300 text-[11px] font-medium hover:bg-slate-50 disabled:opacity-40">‹ Prev</button>
                  <button onClick={() => setPage(p => Math.min(pageCount - 1, p + 1))} disabled={page >= pageCount - 1}
                    className="px-3 py-1 bg-white border border-slate-300 text-[11px] font-medium hover:bg-slate-50 disabled:opacity-40">Next ›</button>
                </div>
              </div>
            )}
          </>
        )}
      </div>

      <HelpModal
        open={showHelp}
        onClose={() => setShowHelp(false)}
        entries={[
          ['Ctrl+F', 'Focus narration filter'],
          ['N', 'New journal entry'],
          ['T / M', 'Today / This month'],
          ['0', 'Division: All'],
          ['1 / 2 / 3', 'Division: Sugar / Power / Ethanol'],
          ['Click row', 'Expand / collapse lines'],
          ['Esc', 'Close modal / clear filters'],
          ['?', 'Show this help'],
        ]}
      />

      <NewJournalEntryModal
        open={newEntryOpen}
        accounts={accounts}
        initialDivision={divisionFilter !== 'ALL' ? divisionFilter : undefined}
        onClose={() => setNewEntryOpen(false)}
        onCreated={() => fetchEntries()}
        onAccountCreated={() => fetchAccounts()}
      />
    </div>
  );
}
