import React, { useState, useEffect, useCallback } from 'react';
import api from '../../services/api';

interface Account {
  id: string;
  code: string;
  name: string;
  type: string;
}

interface JournalLine {
  id: string;
  accountId: string;
  account: { code: string; name: string; type: string };
  debit: number;
  credit: number;
  narration: string | null;
  costCenter: string | null;
}

interface JournalEntryData {
  id: string;
  entryNo: number;
  date: string;
  narration: string;
  refType: string | null;
  isAutoGenerated: boolean;
  isReversed: boolean;
  userId: string;
  createdAt: string;
  lines: JournalLine[];
}

const COST_CENTERS = ['DISTILLERY', 'BOILER', 'DDGS', 'ADMIN', 'TRANSPORT', 'MAINTENANCE'];
const REF_TYPES = ['JOURNAL', 'SALE', 'PURCHASE', 'PAYMENT', 'RECEIPT', 'CONTRA'];

interface FormLine {
  accountId: string;
  debit: string;
  credit: string;
  narration: string;
  costCenter: string;
}

const emptyLine = (): FormLine => ({ accountId: '', debit: '', credit: '', narration: '', costCenter: '' });

export default function JournalEntry() {
  const [entries, setEntries] = useState<JournalEntryData[]>([]);
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [loading, setLoading] = useState(true);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(0);
  const [showForm, setShowForm] = useState(false);
  const [expandedEntry, setExpandedEntry] = useState<string | null>(null);
  const [dateFilter, setDateFilter] = useState({ from: '', to: '' });

  // Form state
  const [form, setForm] = useState({
    date: new Date().toISOString().split('T')[0],
    narration: '',
    refType: 'JOURNAL',
    lines: [emptyLine(), emptyLine()],
  });

  const fetchEntries = useCallback(async () => {
    try {
      setLoading(true);
      const params: Record<string, string> = { limit: '50', offset: String(page * 50) };
      if (dateFilter.from) params.from = dateFilter.from;
      if (dateFilter.to) params.to = dateFilter.to;
      const res = await api.get<{ entries: JournalEntryData[]; total: number }>('/api/journal-entries', { params });
      setEntries(res.data.entries);
      setTotal(res.data.total);
    } catch (err) {
      console.error('Failed to fetch journal entries:', err);
    } finally {
      setLoading(false);
    }
  }, [page, dateFilter]);

  const fetchAccounts = useCallback(async () => {
    try {
      const res = await api.get<Account[]>('/api/chart-of-accounts');
      setAccounts(res.data);
    } catch (err) {
      console.error('Failed to fetch accounts:', err);
    }
  }, []);

  useEffect(() => { fetchEntries(); }, [fetchEntries]);
  useEffect(() => { fetchAccounts(); }, [fetchAccounts]);

  const totalDebit = form.lines.reduce((s, l) => s + (parseFloat(l.debit) || 0), 0);
  const totalCredit = form.lines.reduce((s, l) => s + (parseFloat(l.credit) || 0), 0);
  const difference = Math.abs(totalDebit - totalCredit);
  const isBalanced = difference < 0.01;

  const handleAddLine = () => {
    setForm(f => ({ ...f, lines: [...f.lines, emptyLine()] }));
  };

  const handleRemoveLine = (idx: number) => {
    if (form.lines.length <= 2) return;
    setForm(f => ({ ...f, lines: f.lines.filter((_, i) => i !== idx) }));
  };

  const updateLine = (idx: number, field: keyof FormLine, value: string) => {
    setForm(f => ({
      ...f,
      lines: f.lines.map((l, i) => i === idx ? { ...l, [field]: value } : l),
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!isBalanced) { alert('Debits must equal Credits!'); return; }

    try {
      const payload = {
        date: form.date,
        narration: form.narration,
        refType: form.refType || 'JOURNAL',
        lines: form.lines
          .filter(l => l.accountId && (parseFloat(l.debit) > 0 || parseFloat(l.credit) > 0))
          .map(l => ({
            accountId: l.accountId,
            debit: parseFloat(l.debit) || 0,
            credit: parseFloat(l.credit) || 0,
            narration: l.narration || null,
            costCenter: l.costCenter || null,
          })),
      };

      if (payload.lines.length < 2) { alert('At least 2 lines required (double entry)'); return; }

      await api.post('/api/journal-entries', payload);
      setShowForm(false);
      setForm({ date: new Date().toISOString().split('T')[0], narration: '', refType: 'JOURNAL', lines: [emptyLine(), emptyLine()] });
      await fetchEntries();
    } catch (err: unknown) {
      const msg = (err as { response?: { data?: { error?: string } } })?.response?.data?.error || 'Save failed';
      alert(msg);
    }
  };

  const handleReverse = async (id: string) => {
    if (!confirm('Reverse this journal entry? A new opposite entry will be created.')) return;
    try {
      await api.post(`/api/journal-entries/${id}/reverse`);
      await fetchEntries();
    } catch (err: unknown) {
      const msg = (err as { response?: { data?: { error?: string } } })?.response?.data?.error || 'Reversal failed';
      alert(msg);
    }
  };

  const fmtCurrency = (n: number): string => {
    if (n === 0) return '';
    return '₹' + n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  };

  const fmtDate = (d: string): string => new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });

  if (loading && entries.length === 0) return <div className="p-6 text-gray-500">Loading Journal Entries...</div>;

  return (
    <div className="p-6 space-y-4">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-gray-800">Journal Entries</h1>
        <button
          onClick={() => setShowForm(true)}
          className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
        >
          + New Entry
        </button>
      </div>

      {/* Date Filter */}
      <div className="flex gap-3 items-center">
        <input
          type="date"
          value={dateFilter.from}
          onChange={e => setDateFilter(f => ({ ...f, from: e.target.value }))}
          className="border rounded px-3 py-1.5 text-sm"
        />
        <span className="text-gray-400">to</span>
        <input
          type="date"
          value={dateFilter.to}
          onChange={e => setDateFilter(f => ({ ...f, to: e.target.value }))}
          className="border rounded px-3 py-1.5 text-sm"
        />
        <span className="text-sm text-gray-500">{total} entries</span>
      </div>

      {/* Entries List */}
      <div className="space-y-2">
        {entries.map(entry => (
          <div key={entry.id} className={`bg-white rounded-lg border ${entry.isReversed ? 'opacity-50 border-red-200' : ''}`}>
            <div
              className="flex items-center gap-4 px-4 py-3 cursor-pointer hover:bg-gray-50"
              onClick={() => setExpandedEntry(expandedEntry === entry.id ? null : entry.id)}
            >
              <span className="text-xs font-mono text-gray-400 w-12">#{entry.entryNo}</span>
              <span className="text-sm text-gray-600 w-24">{fmtDate(entry.date)}</span>
              <span className="flex-1 text-sm font-medium">{entry.narration}</span>
              {entry.refType && (
                <span className="text-xs px-2 py-0.5 rounded bg-gray-100 text-gray-600">{entry.refType}</span>
              )}
              {entry.isAutoGenerated && (
                <span className="text-xs px-2 py-0.5 rounded bg-blue-50 text-blue-600">Auto</span>
              )}
              {entry.isReversed && (
                <span className="text-xs px-2 py-0.5 rounded bg-red-50 text-red-600">Reversed</span>
              )}
              <span className="text-sm font-mono text-gray-700 w-28 text-right">
                {fmtCurrency(entry.lines.reduce((s, l) => s + l.debit, 0))}
              </span>
              <span className="text-gray-400">{expandedEntry === entry.id ? '▲' : '▼'}</span>
            </div>

            {expandedEntry === entry.id && (
              <div className="border-t px-4 py-3 bg-gray-50">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="text-xs text-gray-500">
                      <th className="text-left py-1">Account</th>
                      <th className="text-left py-1">Narration</th>
                      <th className="text-left py-1">Cost Center</th>
                      <th className="text-right py-1">Debit (₹)</th>
                      <th className="text-right py-1">Credit (₹)</th>
                    </tr>
                  </thead>
                  <tbody>
                    {entry.lines.map(line => (
                      <tr key={line.id} className="border-t border-gray-100">
                        <td className="py-1.5">
                          <span className="font-mono text-xs text-gray-400 mr-1">{line.account.code}</span>
                          {line.account.name}
                        </td>
                        <td className="py-1.5 text-gray-500 text-xs">{line.narration || '—'}</td>
                        <td className="py-1.5 text-gray-500 text-xs">{line.costCenter || '—'}</td>
                        <td className="py-1.5 text-right font-mono">{fmtCurrency(line.debit)}</td>
                        <td className="py-1.5 text-right font-mono">{fmtCurrency(line.credit)}</td>
                      </tr>
                    ))}
                  </tbody>
                  <tfoot>
                    <tr className="border-t font-medium">
                      <td colSpan={3} className="py-1.5 text-right text-xs text-gray-500">Total</td>
                      <td className="py-1.5 text-right font-mono">{fmtCurrency(entry.lines.reduce((s, l) => s + l.debit, 0))}</td>
                      <td className="py-1.5 text-right font-mono">{fmtCurrency(entry.lines.reduce((s, l) => s + l.credit, 0))}</td>
                    </tr>
                  </tfoot>
                </table>
                {!entry.isReversed && !entry.isAutoGenerated && (
                  <button
                    onClick={() => handleReverse(entry.id)}
                    className="mt-2 text-xs text-red-600 hover:underline"
                  >
                    ↩ Reverse Entry
                  </button>
                )}
              </div>
            )}
          </div>
        ))}
        {entries.length === 0 && (
          <div className="text-center py-12 text-gray-400">No journal entries found</div>
        )}
      </div>

      {/* Pagination */}
      {total > 50 && (
        <div className="flex gap-2 justify-center">
          <button
            onClick={() => setPage(p => Math.max(0, p - 1))}
            disabled={page === 0}
            className="px-3 py-1 rounded text-sm bg-gray-100 disabled:opacity-50"
          >
            ← Prev
          </button>
          <span className="px-3 py-1 text-sm text-gray-500">Page {page + 1} of {Math.ceil(total / 50)}</span>
          <button
            onClick={() => setPage(p => p + 1)}
            disabled={(page + 1) * 50 >= total}
            className="px-3 py-1 rounded text-sm bg-gray-100 disabled:opacity-50"
          >
            Next →
          </button>
        </div>
      )}

      {/* New Entry Form Modal */}
      {showForm && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 overflow-y-auto py-8">
          <form onSubmit={handleSubmit} className="bg-white rounded-xl shadow-lg p-6 w-full max-w-3xl space-y-4">
            <h2 className="text-lg font-bold">New Journal Entry</h2>

            <div className="grid grid-cols-3 gap-3">
              <div>
                <label className="block text-xs font-medium text-gray-600 mb-1">Date</label>
                <input
                  type="date"
                  value={form.date}
                  onChange={e => setForm(f => ({ ...f, date: e.target.value }))}
                  className="w-full border rounded px-3 py-2 text-sm"
                  required
                />
              </div>
              <div>
                <label className="block text-xs font-medium text-gray-600 mb-1">Type</label>
                <select
                  value={form.refType}
                  onChange={e => setForm(f => ({ ...f, refType: e.target.value }))}
                  className="w-full border rounded px-3 py-2 text-sm"
                >
                  {REF_TYPES.map(t => <option key={t} value={t}>{t}</option>)}
                </select>
              </div>
              <div>
                <label className="block text-xs font-medium text-gray-600 mb-1">Narration</label>
                <input
                  value={form.narration}
                  onChange={e => setForm(f => ({ ...f, narration: e.target.value }))}
                  className="w-full border rounded px-3 py-2 text-sm"
                  placeholder="e.g. Office rent for March 2026"
                  required
                />
              </div>
            </div>

            {/* Lines */}
            <div className="border rounded-lg overflow-hidden">
              <table className="w-full text-sm">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="text-left px-3 py-2 text-xs font-medium text-gray-600">Account</th>
                    <th className="text-left px-3 py-2 text-xs font-medium text-gray-600 w-28">Debit (₹)</th>
                    <th className="text-left px-3 py-2 text-xs font-medium text-gray-600 w-28">Credit (₹)</th>
                    <th className="text-left px-3 py-2 text-xs font-medium text-gray-600 w-32">Cost Center</th>
                    <th className="w-8"></th>
                  </tr>
                </thead>
                <tbody>
                  {form.lines.map((line, idx) => (
                    <tr key={idx} className="border-t">
                      <td className="px-3 py-1.5">
                        <select
                          value={line.accountId}
                          onChange={e => updateLine(idx, 'accountId', e.target.value)}
                          className="w-full border rounded px-2 py-1.5 text-sm"
                          required
                        >
                          <option value="">Select Account</option>
                          {accounts.map(a => (
                            <option key={a.id} value={a.id}>{a.code} — {a.name}</option>
                          ))}
                        </select>
                      </td>
                      <td className="px-3 py-1.5">
                        <input
                          type="number"
                          step="0.01"
                          min="0"
                          value={line.debit}
                          onChange={e => {
                            updateLine(idx, 'debit', e.target.value);
                            if (parseFloat(e.target.value) > 0) updateLine(idx, 'credit', '');
                          }}
                          className="w-full border rounded px-2 py-1.5 text-sm text-right"
                          placeholder="0.00"
                        />
                      </td>
                      <td className="px-3 py-1.5">
                        <input
                          type="number"
                          step="0.01"
                          min="0"
                          value={line.credit}
                          onChange={e => {
                            updateLine(idx, 'credit', e.target.value);
                            if (parseFloat(e.target.value) > 0) updateLine(idx, 'debit', '');
                          }}
                          className="w-full border rounded px-2 py-1.5 text-sm text-right"
                          placeholder="0.00"
                        />
                      </td>
                      <td className="px-3 py-1.5">
                        <select
                          value={line.costCenter}
                          onChange={e => updateLine(idx, 'costCenter', e.target.value)}
                          className="w-full border rounded px-2 py-1.5 text-sm"
                        >
                          <option value="">—</option>
                          {COST_CENTERS.map(cc => <option key={cc} value={cc}>{cc}</option>)}
                        </select>
                      </td>
                      <td className="px-1">
                        {form.lines.length > 2 && (
                          <button type="button" onClick={() => handleRemoveLine(idx)} className="text-red-400 hover:text-red-600 text-lg">×</button>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
                <tfoot>
                  <tr className="border-t bg-gray-50 font-medium">
                    <td className="px-3 py-2 text-right text-xs text-gray-500">Total</td>
                    <td className="px-3 py-2 text-right font-mono text-sm">{fmtCurrency(totalDebit)}</td>
                    <td className="px-3 py-2 text-right font-mono text-sm">{fmtCurrency(totalCredit)}</td>
                    <td colSpan={2} className="px-3 py-2">
                      {!isBalanced && difference > 0 && (
                        <span className="text-xs text-red-600">Diff: ₹{difference.toFixed(2)}</span>
                      )}
                      {isBalanced && totalDebit > 0 && (
                        <span className="text-xs text-green-600">✓ Balanced</span>
                      )}
                    </td>
                  </tr>
                </tfoot>
              </table>
            </div>

            <button type="button" onClick={handleAddLine} className="text-sm text-blue-600 hover:underline">
              + Add Line
            </button>

            <div className="flex gap-2 justify-end pt-2">
              <button
                type="button"
                onClick={() => setShowForm(false)}
                className="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={!isBalanced || totalDebit === 0}
                className="px-4 py-2 text-sm bg-blue-600 text-white rounded hover:bg-blue-700 disabled:opacity-50"
              >
                Save Entry
              </button>
            </div>
          </form>
        </div>
      )}
    </div>
  );
}
