/**
 * Auto-Journal Engine — Automated Double-Entry Bookkeeping
 *
 * Every financial transaction in the ERP automatically generates journal entries.
 * This eliminates manual bookkeeping and ensures the general ledger is always in sync.
 *
 * Trigger points:
 * - Sale Invoice created → Dr Receivable, Cr Sales + GST
 * - Sale Payment received → Dr Bank/Cash, Cr Receivable
 * - GRN confirmed → Dr Inventory/Expense, Cr Payable
 * - Vendor Payment made → Dr Payable, Cr Bank/Cash
 * - Shipment payment confirmed → Dr Bank/Cash, Cr Receivable
 * - Stock movement → Dr/Cr Inventory, Cr/Dr COGS/WIP
 */

import { PrismaClient } from '@prisma/client';

// Account codes — must match seeded Chart of Accounts
const ACCT = {
  // Assets
  CASH: '1001',
  SBI_BANK: '1002',
  HDFC_BANK: '1003',
  TRADE_RECEIVABLE: '1100',
  INVENTORY: '1400',
  ADVANCE_TO_SUPPLIERS: '1600',
  // Liabilities
  TRADE_PAYABLE: '2001',
  CONTRACTOR_PAYABLE: '2002',
  GST_OUTPUT_CGST: '2100',
  GST_OUTPUT_SGST: '2101',
  GST_OUTPUT_IGST: '2102',
  GST_INPUT_CGST: '1200',
  GST_INPUT_SGST: '1201',
  GST_INPUT_IGST: '1202',
  TDS_PAYABLE: '2200',
  LOANS_BANK: '2400',
  // Income
  ETHANOL_SALES: '3001',
  DDGS_SALES: '3002',
  OTHER_INCOME: '3003',
  INTEREST_INCOME: '3004',
  // Expenses
  GRAIN_PURCHASE: '4001',
  CHEMICAL_PURCHASE: '4002',
  UTILITY_EXPENSE: '4003',
  TRANSPORT_EXPENSE: '4010',
  SALARY_EXPENSE: '4020',
  MAINTENANCE_EXPENSE: '4030',
  CONTRACTOR_EXPENSE: '4035',
  OTHER_EXPENSE: '4040',
  DEPRECIATION: '4050',
  INTEREST_EXPENSE: '4090',
  COGS: '4009',
  // Equity
  CAPITAL: '5001',
  RETAINED_EARNINGS: '5002',
} as const;

// Payment mode → account mapping
const PAYMENT_ACCOUNT: Record<string, string> = {
  'CASH': ACCT.CASH,
  'UPI': ACCT.SBI_BANK,
  'NEFT': ACCT.SBI_BANK,
  'RTGS': ACCT.SBI_BANK,
  'CHEQUE': ACCT.SBI_BANK,
  'BANK_TRANSFER': ACCT.SBI_BANK,
};

// Product → sales account mapping
function getSalesAccountCode(productName: string): string {
  const p = (productName || '').toUpperCase();
  if (p.includes('ETHANOL') || p.includes('ENA') || p.includes('RS') || p.includes('RECTIFIED')) return ACCT.ETHANOL_SALES;
  if (p.includes('DDGS') || p.includes('DISTILLER')) return ACCT.DDGS_SALES;
  return ACCT.OTHER_INCOME;
}

// Category → expense account mapping
function getExpenseAccountCode(category: string): string {
  const c = (category || '').toUpperCase();
  if (c.includes('GRAIN') || c.includes('RAW')) return ACCT.GRAIN_PURCHASE;
  if (c.includes('CHEMICAL')) return ACCT.CHEMICAL_PURCHASE;
  if (c.includes('SPARE') || c.includes('MAINTENANCE')) return ACCT.MAINTENANCE_EXPENSE;
  if (c.includes('UTILITY')) return ACCT.UTILITY_EXPENSE;
  return ACCT.OTHER_EXPENSE;
}

interface AccountCache {
  [code: string]: string; // code → id
}

/** Resolve account codes to IDs (cached per call) */
async function resolveAccounts(prisma: PrismaClient, codes: string[]): Promise<AccountCache> {
  const uniqueCodes = [...new Set(codes)];
  const accounts = await prisma.account.findMany({
    where: { code: { in: uniqueCodes }, isActive: true },
    select: { id: true, code: true },
  });
  const cache: AccountCache = {};
  for (const a of accounts) cache[a.code] = a.id;
  return cache;
}

/** Helper: create journal entry with lines in a transaction */
async function createJournalEntry(
  tx: any,
  params: {
    date: Date;
    narration: string;
    refType: string;
    refId: string;
    userId: string;
    lines: { accountId: string; debit: number; credit: number; narration?: string; costCenter?: string }[];
  }
): Promise<string> {
  // Dedup check: skip if a non-reversed entry already exists for same refType+refId
  if (params.refType && params.refId) {
    const existing = await tx.journalEntry.findFirst({
      where: { refType: params.refType, refId: params.refId, isReversed: false },
    });
    if (existing) {
      console.warn(`[AutoJournal] Skipping duplicate: ${params.refType}/${params.refId} already has entry #${existing.entryNo}`);
      return existing.id;
    }
  }

  // Validate debits = credits
  const totalDebit = params.lines.reduce((s, l) => s + l.debit, 0);
  const totalCredit = params.lines.reduce((s, l) => s + l.credit, 0);
  if (Math.abs(totalDebit - totalCredit) > 0.01) {
    throw new Error(`Journal unbalanced: debit=${totalDebit}, credit=${totalCredit}`);
  }

  const entry = await tx.journalEntry.create({
    data: {
      date: params.date,
      narration: params.narration,
      refType: params.refType,
      refId: params.refId,
      isAutoGenerated: true,
      userId: params.userId,
      lines: {
        create: params.lines.map(l => ({
          accountId: l.accountId,
          debit: Math.round(l.debit * 100) / 100,
          credit: Math.round(l.credit * 100) / 100,
          narration: l.narration,
          costCenter: l.costCenter || 'DISTILLERY',
        })),
      },
    },
  });

  return entry.id;
}

// ═══════════════════════════════════════════════════════
// SALE INVOICE → Journal Entry
// Dr Trade Receivable (totalAmount)
//   Cr Sales Revenue (amount before GST)
//   Cr GST Output CGST (cgst)
//   Cr GST Output SGST (sgst) — or IGST for interstate
// ═══════════════════════════════════════════════════════
export async function onSaleInvoiceCreated(
  prisma: PrismaClient,
  invoice: {
    id: string;
    invoiceNo: number;
    totalAmount: number;
    amount: number;
    gstAmount: number;
    gstPercent: number;
    cgstAmount?: number;
    sgstAmount?: number;
    igstAmount?: number;
    supplyType?: string;
    freightCharge?: number;
    productName: string;
    customerId: string;
    userId: string;
    invoiceDate: Date;
    customer?: { state?: string | null } | null;
  }
): Promise<string | null> {
  try {
    const isInterstate = invoice.supplyType === 'INTER_STATE' || (!invoice.supplyType && invoice.customer?.state && invoice.customer.state !== 'Madhya Pradesh');
    const salesCode = getSalesAccountCode(invoice.productName);
    const gstCodes = isInterstate
      ? [ACCT.GST_OUTPUT_IGST]
      : [ACCT.GST_OUTPUT_CGST, ACCT.GST_OUTPUT_SGST];

    const allCodes = [ACCT.TRADE_RECEIVABLE, salesCode, ...gstCodes];
    const accts = await resolveAccounts(prisma, allCodes);

    // Check all accounts exist
    for (const code of allCodes) {
      if (!accts[code]) return null; // Accounts not seeded yet
    }

    // Credit sales revenue includes freight recovery to keep journal balanced
    const salesCredit = invoice.amount + (invoice.freightCharge || 0);
    const lines: { accountId: string; debit: number; credit: number; narration?: string }[] = [
      { accountId: accts[ACCT.TRADE_RECEIVABLE], debit: invoice.totalAmount, credit: 0, narration: `INV-${invoice.invoiceNo}` },
      { accountId: accts[salesCode], debit: 0, credit: salesCredit, narration: `${invoice.productName} sale${invoice.freightCharge ? ' + freight' : ''}` },
    ];

    if (isInterstate) {
      const igst = invoice.igstAmount ?? invoice.gstAmount;
      lines.push({ accountId: accts[ACCT.GST_OUTPUT_IGST], debit: 0, credit: igst, narration: `IGST @${invoice.gstPercent}%` });
    } else {
      const cgst = invoice.cgstAmount ?? invoice.gstAmount / 2;
      const sgst = invoice.sgstAmount ?? (invoice.gstAmount - cgst);
      lines.push({ accountId: accts[ACCT.GST_OUTPUT_CGST], debit: 0, credit: cgst, narration: `CGST @${invoice.gstPercent / 2}%` });
      lines.push({ accountId: accts[ACCT.GST_OUTPUT_SGST], debit: 0, credit: sgst, narration: `SGST @${invoice.gstPercent / 2}%` });
    }

    return await prisma.$transaction(async (tx: any) => {
      return createJournalEntry(tx, {
        date: invoice.invoiceDate,
        narration: `Sale Invoice INV-${invoice.invoiceNo} — ${invoice.productName}`,
        refType: 'SALE',
        refId: invoice.id,
        userId: invoice.userId,
        lines,
      });
    });
  } catch (err) {
    console.error('[AutoJournal] Failed to create sale invoice journal:', err);
    return null;
  }
}

// ═══════════════════════════════════════════════════════
// SALE PAYMENT RECEIVED → Journal Entry
// Dr Bank/Cash (amount)
//   Cr Trade Receivable (amount)
// ═══════════════════════════════════════════════════════
export async function onSalePaymentReceived(
  prisma: PrismaClient,
  payment: {
    id: string;
    amount: number;
    mode: string;
    reference?: string | null;
    paymentDate: Date;
    customerId: string;
    invoiceId?: string | null;
    userId: string;
  }
): Promise<string | null> {
  try {
    const bankCode = PAYMENT_ACCOUNT[payment.mode] || ACCT.SBI_BANK;
    const accts = await resolveAccounts(prisma, [bankCode, ACCT.TRADE_RECEIVABLE]);
    if (!accts[bankCode] || !accts[ACCT.TRADE_RECEIVABLE]) return null;

    return await prisma.$transaction(async (tx: any) => {
      return createJournalEntry(tx, {
        date: payment.paymentDate,
        narration: `Payment received — ${payment.mode} ${payment.reference || ''}`.trim(),
        refType: 'RECEIPT',
        refId: payment.id,
        userId: payment.userId,
        lines: [
          { accountId: accts[bankCode], debit: payment.amount, credit: 0, narration: `${payment.mode} ${payment.reference || ''}`.trim() },
          { accountId: accts[ACCT.TRADE_RECEIVABLE], debit: 0, credit: payment.amount },
        ],
      });
    });
  } catch (err) {
    console.error('[AutoJournal] Failed to create sale payment journal:', err);
    return null;
  }
}

// ═══════════════════════════════════════════════════════
// SHIPMENT PAYMENT CONFIRMED → Journal Entry
// Dr Bank/Cash (amount)
//   Cr Trade Receivable (amount)
// ═══════════════════════════════════════════════════════
export async function onShipmentPaymentConfirmed(
  prisma: PrismaClient,
  shipment: {
    id: string;
    shipmentNo: number;
    paymentAmount: number;
    paymentMode: string;
    paymentRef?: string | null;
    userId: string;
  }
): Promise<string | null> {
  try {
    const bankCode = PAYMENT_ACCOUNT[shipment.paymentMode] || ACCT.SBI_BANK;
    const accts = await resolveAccounts(prisma, [bankCode, ACCT.TRADE_RECEIVABLE]);
    if (!accts[bankCode] || !accts[ACCT.TRADE_RECEIVABLE]) return null;

    return await prisma.$transaction(async (tx: any) => {
      return createJournalEntry(tx, {
        date: new Date(),
        narration: `Shipment #${shipment.shipmentNo} payment — ${shipment.paymentMode} ${shipment.paymentRef || ''}`.trim(),
        refType: 'RECEIPT',
        refId: shipment.id,
        userId: shipment.userId,
        lines: [
          { accountId: accts[bankCode], debit: shipment.paymentAmount, credit: 0, narration: `${shipment.paymentMode} ${shipment.paymentRef || ''}`.trim() },
          { accountId: accts[ACCT.TRADE_RECEIVABLE], debit: 0, credit: shipment.paymentAmount },
        ],
      });
    });
  } catch (err) {
    console.error('[AutoJournal] Failed to create shipment payment journal:', err);
    return null;
  }
}

// ═══════════════════════════════════════════════════════
// GRN / PURCHASE INVOICE → Journal Entry
// Dr Expense/Inventory (amount before GST)
// Dr GST Input CGST + SGST (or IGST)
//   Cr Trade Payable (total)
// ═══════════════════════════════════════════════════════
export async function onPurchaseBooked(
  prisma: PrismaClient,
  purchase: {
    id: string;
    refNo: string;
    totalAmount: number;
    baseAmount: number;
    gstAmount: number;
    gstPercent: number;
    category: string;
    vendorId: string;
    userId: string;
    date: Date;
    isInterstate?: boolean;
  }
): Promise<string | null> {
  try {
    const expenseCode = getExpenseAccountCode(purchase.category);
    const isInterstate = purchase.isInterstate || false;
    const gstCodes = isInterstate
      ? [ACCT.GST_INPUT_IGST]
      : [ACCT.GST_INPUT_CGST, ACCT.GST_INPUT_SGST];

    const allCodes = [expenseCode, ACCT.TRADE_PAYABLE, ...gstCodes];
    const accts = await resolveAccounts(prisma, allCodes);
    for (const code of allCodes) {
      if (!accts[code]) return null;
    }

    const lines: { accountId: string; debit: number; credit: number; narration?: string }[] = [
      { accountId: accts[expenseCode], debit: purchase.baseAmount, credit: 0, narration: purchase.refNo },
    ];

    if (purchase.gstAmount > 0) {
      if (isInterstate) {
        lines.push({ accountId: accts[ACCT.GST_INPUT_IGST], debit: purchase.gstAmount, credit: 0, narration: `IGST @${purchase.gstPercent}%` });
      } else {
        const halfGst = purchase.gstAmount / 2;
        lines.push({ accountId: accts[ACCT.GST_INPUT_CGST], debit: halfGst, credit: 0, narration: `CGST @${purchase.gstPercent / 2}%` });
        lines.push({ accountId: accts[ACCT.GST_INPUT_SGST], debit: halfGst, credit: 0, narration: `SGST @${purchase.gstPercent / 2}%` });
      }
    }

    lines.push({ accountId: accts[ACCT.TRADE_PAYABLE], debit: 0, credit: purchase.totalAmount, narration: purchase.refNo });

    return await prisma.$transaction(async (tx: any) => {
      return createJournalEntry(tx, {
        date: purchase.date,
        narration: `Purchase — ${purchase.refNo}`,
        refType: 'PURCHASE',
        refId: purchase.id,
        userId: purchase.userId,
        lines,
      });
    });
  } catch (err) {
    console.error('[AutoJournal] Failed to create purchase journal:', err);
    return null;
  }
}

// ═══════════════════════════════════════════════════════
// VENDOR PAYMENT → Journal Entry
// Dr Trade Payable (amount + tds)
//   Cr Bank/Cash (amount)
//   Cr TDS Payable (tds, if any)
// ═══════════════════════════════════════════════════════
export async function onVendorPaymentMade(
  prisma: PrismaClient,
  payment: {
    id: string;
    amount: number;
    mode: string;
    reference?: string | null;
    tdsDeducted: number;
    vendorId: string;
    userId: string;
    paymentDate: Date;
  }
): Promise<string | null> {
  try {
    const bankCode = PAYMENT_ACCOUNT[payment.mode] || ACCT.SBI_BANK;
    const codes = [bankCode, ACCT.TRADE_PAYABLE];
    if (payment.tdsDeducted > 0) codes.push(ACCT.TDS_PAYABLE);

    const accts = await resolveAccounts(prisma, codes);
    for (const code of codes) {
      if (!accts[code]) return null;
    }

    const totalSettled = payment.amount + payment.tdsDeducted;
    const lines: { accountId: string; debit: number; credit: number; narration?: string }[] = [
      { accountId: accts[ACCT.TRADE_PAYABLE], debit: totalSettled, credit: 0, narration: `Payment ${payment.reference || ''}`.trim() },
      { accountId: accts[bankCode], debit: 0, credit: payment.amount, narration: `${payment.mode} ${payment.reference || ''}`.trim() },
    ];

    if (payment.tdsDeducted > 0) {
      lines.push({ accountId: accts[ACCT.TDS_PAYABLE], debit: 0, credit: payment.tdsDeducted, narration: `TDS deducted` });
    }

    return await prisma.$transaction(async (tx: any) => {
      return createJournalEntry(tx, {
        date: payment.paymentDate,
        narration: `Vendor payment — ${payment.mode} ${payment.reference || ''}`.trim(),
        refType: 'PAYMENT',
        refId: payment.id,
        userId: payment.userId,
        lines,
      });
    });
  } catch (err) {
    console.error('[AutoJournal] Failed to create vendor payment journal:', err);
    return null;
  }
}

// ═══════════════════════════════════════════════════════
// STOCK MOVEMENT → Journal Entry
// Receipt: Dr Inventory, Cr GRN Clearing/Payable
// Issue: Dr COGS/WIP, Cr Inventory
// Adjustment: Dr/Cr Inventory, Cr/Dr Inventory Adjustment
// ═══════════════════════════════════════════════════════
export async function onStockMovement(
  prisma: PrismaClient,
  movement: {
    id: string;
    movementNo: number;
    movementType: string;
    direction: string;
    totalValue: number;
    itemName: string;
    userId: string;
    date: Date;
  }
): Promise<string | null> {
  try {
    if (movement.totalValue <= 0) return null; // No value movements don't need journals

    const accts = await resolveAccounts(prisma, [ACCT.INVENTORY, ACCT.COGS, ACCT.TRADE_PAYABLE, ACCT.OTHER_EXPENSE]);
    if (!accts[ACCT.INVENTORY]) return null;

    let lines: { accountId: string; debit: number; credit: number; narration?: string; costCenter?: string }[] = [];

    if (movement.direction === 'IN') {
      // Dr Inventory, Cr Payable (for GRN) or Other (for production/adjustment)
      const creditAcct = movement.movementType === 'GRN_RECEIPT'
        ? (accts[ACCT.TRADE_PAYABLE] || accts[ACCT.OTHER_EXPENSE])
        : (accts[ACCT.OTHER_EXPENSE] || accts[ACCT.TRADE_PAYABLE]);

      if (!creditAcct) return null;

      lines = [
        { accountId: accts[ACCT.INVENTORY], debit: movement.totalValue, credit: 0, narration: `${movement.movementType} — ${movement.itemName}` },
        { accountId: creditAcct, debit: 0, credit: movement.totalValue, narration: `Stock receipt #${movement.movementNo}` },
      ];
    } else {
      // Dr COGS/Expense, Cr Inventory
      const debitAcct = movement.movementType === 'SALES_ISSUE'
        ? (accts[ACCT.COGS] || accts[ACCT.OTHER_EXPENSE])
        : (accts[ACCT.OTHER_EXPENSE] || accts[ACCT.COGS]);

      if (!debitAcct) return null;

      lines = [
        { accountId: debitAcct, debit: movement.totalValue, credit: 0, narration: `${movement.movementType} — ${movement.itemName}` },
        { accountId: accts[ACCT.INVENTORY], debit: 0, credit: movement.totalValue, narration: `Stock issue #${movement.movementNo}` },
      ];
    }

    return await prisma.$transaction(async (tx: any) => {
      return createJournalEntry(tx, {
        date: movement.date,
        narration: `Stock ${movement.direction === 'IN' ? 'receipt' : 'issue'} #${movement.movementNo} — ${movement.itemName}`,
        refType: movement.movementType === 'GRN_RECEIPT' ? 'PURCHASE' : movement.movementType === 'SALES_ISSUE' ? 'SALE' : 'JOURNAL',
        refId: movement.id,
        userId: movement.userId,
        lines,
      });
    });
  } catch (err) {
    console.error('[AutoJournal] Failed to create stock movement journal:', err);
    return null;
  }
}

// ═══════════════════════════════════════════════════════
// TRANSPORTER PAYMENT → Journal Entry
// Dr Transport Expense (freight amount)
//   Cr Bank/Cash (amount paid)
// ═══════════════════════════════════════════════════════
export async function onTransporterPaymentMade(
  prisma: PrismaClient,
  payment: {
    id: string;
    amount: number;
    mode: string;
    reference?: string | null;
    transporterName: string;
    shipmentId?: string | null;
    userId: string;
    paymentDate: Date;
  }
): Promise<string | null> {
  try {
    if (payment.amount <= 0) return null;

    const bankCode = PAYMENT_ACCOUNT[payment.mode] || ACCT.SBI_BANK;
    const accts = await resolveAccounts(prisma, [bankCode, ACCT.TRANSPORT_EXPENSE]);
    if (!accts[bankCode] || !accts[ACCT.TRANSPORT_EXPENSE]) return null;

    return await prisma.$transaction(async (tx: any) => {
      return createJournalEntry(tx, {
        date: payment.paymentDate,
        narration: `Freight payment to ${payment.transporterName} — ${payment.mode} ${payment.reference || ''}`.trim(),
        refType: 'PAYMENT',
        refId: payment.id,
        userId: payment.userId,
        lines: [
          { accountId: accts[ACCT.TRANSPORT_EXPENSE], debit: payment.amount, credit: 0, narration: `Freight — ${payment.transporterName}` },
          { accountId: accts[bankCode], debit: 0, credit: payment.amount, narration: `${payment.mode} ${payment.reference || ''}`.trim() },
        ],
      });
    });
  } catch (err) {
    console.error('[AutoJournal] Failed to create transporter payment journal:', err);
    return null;
  }
}

// ═══════════════════════════════════════════════════════
// TRADER ADVANCE → Journal Entry
// Dr. Advance to Suppliers (asset 1600), Cr. Bank/Cash
// ═══════════════════════════════════════════════════════

export async function createAdvanceJournal(
  prisma: PrismaClient,
  payment: {
    id: string;
    amount: number;
    mode: string;
    reference?: string | null;
    vendorId: string;
    userId: string;
    paymentDate: Date;
  }
): Promise<string | null> {
  try {
    const bankCode = PAYMENT_ACCOUNT[payment.mode] || ACCT.SBI_BANK;
    const accts = await resolveAccounts(prisma, [bankCode, ACCT.ADVANCE_TO_SUPPLIERS]);
    if (!accts[bankCode] || !accts[ACCT.ADVANCE_TO_SUPPLIERS]) return null;

    return await prisma.$transaction(async (tx: any) => {
      return createJournalEntry(tx, {
        date: payment.paymentDate,
        narration: `Advance to trader — ${payment.mode} ${payment.reference || ''}`.trim(),
        refType: 'ADVANCE',
        refId: payment.id,
        userId: payment.userId,
        lines: [
          { accountId: accts[ACCT.ADVANCE_TO_SUPPLIERS], debit: payment.amount, credit: 0, narration: `Advance ${payment.reference || ''}`.trim() },
          { accountId: accts[bankCode], debit: 0, credit: payment.amount, narration: `${payment.mode} ${payment.reference || ''}`.trim() },
        ],
      });
    });
  } catch (err) {
    console.error('[AutoJournal] Failed to create advance journal:', err);
    return null;
  }
}

// ═══════════════════════════════════════════════════════
// CONTRACTOR BILL CONFIRMED → Journal Entry (Accrual)
// ═══════════════════════════════════════════════════════
export async function onContractorBillConfirmed(
  prisma: PrismaClient,
  bill: {
    id: string; billNo: number; subtotal: number;
    cgstAmount: number; sgstAmount: number; igstAmount: number;
    totalAmount: number; tdsAmount: number; netPayable: number;
    contractorId: string; contractorName: string; userId: string; billDate: Date;
  }
): Promise<string | null> {
  try {
    const gstCodes: string[] = [];
    if (bill.igstAmount > 0) gstCodes.push(ACCT.GST_INPUT_IGST);
    if (bill.cgstAmount > 0) gstCodes.push(ACCT.GST_INPUT_CGST);
    if (bill.sgstAmount > 0) gstCodes.push(ACCT.GST_INPUT_SGST);
    const allCodes = [ACCT.CONTRACTOR_EXPENSE, ACCT.CONTRACTOR_PAYABLE, ...gstCodes];
    if (bill.tdsAmount > 0) allCodes.push(ACCT.TDS_PAYABLE);
    const accts = await resolveAccounts(prisma, allCodes);
    for (const code of allCodes) { if (!accts[code]) return null; }

    const lines: { accountId: string; debit: number; credit: number; narration?: string }[] = [
      { accountId: accts[ACCT.CONTRACTOR_EXPENSE], debit: bill.subtotal, credit: 0, narration: `Bill #${bill.billNo} — ${bill.contractorName}` },
    ];
    if (bill.igstAmount > 0) lines.push({ accountId: accts[ACCT.GST_INPUT_IGST], debit: bill.igstAmount, credit: 0, narration: `IGST on contractor bill` });
    if (bill.cgstAmount > 0) lines.push({ accountId: accts[ACCT.GST_INPUT_CGST], debit: bill.cgstAmount, credit: 0, narration: `CGST on contractor bill` });
    if (bill.sgstAmount > 0) lines.push({ accountId: accts[ACCT.GST_INPUT_SGST], debit: bill.sgstAmount, credit: 0, narration: `SGST on contractor bill` });
    lines.push({ accountId: accts[ACCT.CONTRACTOR_PAYABLE], debit: 0, credit: bill.netPayable, narration: `Payable — Bill #${bill.billNo}` });
    if (bill.tdsAmount > 0) lines.push({ accountId: accts[ACCT.TDS_PAYABLE], debit: 0, credit: bill.tdsAmount, narration: `TDS u/s 194C — ${bill.contractorName}` });

    return await prisma.$transaction(async (tx: any) => {
      return createJournalEntry(tx, {
        date: bill.billDate, narration: `Contractor bill #${bill.billNo} — ${bill.contractorName}`,
        refType: 'CONTRACTOR_BILL', refId: bill.id, userId: bill.userId, lines,
      });
    });
  } catch (err) { console.error('[AutoJournal] Failed to create contractor bill journal:', err); return null; }
}

// ═══════════════════════════════════════════════════════
// CONTRACTOR PAYMENT → Journal Entry
// ═══════════════════════════════════════════════════════
export async function onContractorPaymentMade(
  prisma: PrismaClient,
  payment: {
    id: string; amount: number; mode: string; reference?: string | null;
    tdsDeducted: number; contractorId: string; contractorName: string;
    userId: string; paymentDate: Date;
  }
): Promise<string | null> {
  try {
    const bankCode = PAYMENT_ACCOUNT[payment.mode] || ACCT.SBI_BANK;
    const codes = [bankCode, ACCT.CONTRACTOR_PAYABLE];
    if (payment.tdsDeducted > 0) codes.push(ACCT.TDS_PAYABLE);
    const accts = await resolveAccounts(prisma, codes);
    for (const code of codes) { if (!accts[code]) return null; }

    const totalSettled = payment.amount + payment.tdsDeducted;
    const lines: { accountId: string; debit: number; credit: number; narration?: string }[] = [
      { accountId: accts[ACCT.CONTRACTOR_PAYABLE], debit: totalSettled, credit: 0, narration: `Payment ${payment.reference || ''}`.trim() },
      { accountId: accts[bankCode], debit: 0, credit: payment.amount, narration: `${payment.mode} ${payment.reference || ''}`.trim() },
    ];
    if (payment.tdsDeducted > 0) lines.push({ accountId: accts[ACCT.TDS_PAYABLE], debit: 0, credit: payment.tdsDeducted, narration: `TDS u/s 194C` });

    return await prisma.$transaction(async (tx: any) => {
      return createJournalEntry(tx, {
        date: payment.paymentDate, narration: `Contractor payment to ${payment.contractorName} — ${payment.mode} ${payment.reference || ''}`.trim(),
        refType: 'CONTRACTOR_PAYMENT', refId: payment.id, userId: payment.userId, lines,
      });
    });
  } catch (err) { console.error('[AutoJournal] Failed to create contractor payment journal:', err); return null; }
}

export { ACCT, PAYMENT_ACCOUNT };
