/**
 * Invoice Snapshot Service — freeze invoice as JSON + PDF at IRN-generation time.
 *
 * Spec: .claude/skills/invoice-snapshot-immutability.md
 * Phase 1 (this file): shadow-write only. Read path (GET /:id/pdf) still renders
 * from live DB. Snapshots are written in the background after IRN success and never
 * block the request.
 *
 * freezeInvoice(invoiceId) is fire-and-forget from the caller's perspective:
 * - Never throws — logs errors instead
 * - IRN at NIC is already generated by the time we get here; we cannot rollback
 * - If write fails, the Invoice row still has irn/ackNo/signedQRCode intact
 */

import { createHash } from 'crypto';
import { promises as fs } from 'fs';
import path from 'path';
import prisma from '../config/prisma';
import { renderDocumentPdf } from './documentRenderer';
import { getCompanyForPdf } from '../utils/pdfCompanyHelper';

// Resolution order:
//   1. Explicit SNAPSHOT_DIR env var (user override)
//   2. Railway-injected volume mount path (survives redeploys) + /snapshots
//   3. Local public/snapshots folder (dev + ephemeral fallback — survives only until next deploy)
const SNAPSHOT_DIR = process.env.SNAPSHOT_DIR
  || (process.env.RAILWAY_VOLUME_MOUNT_PATH
        ? path.join(process.env.RAILWAY_VOLUME_MOUNT_PATH, 'invoice-snapshots')
        : path.resolve(__dirname, '..', '..', 'public', 'snapshots'));
const SCHEMA_VERSION = 1;

export interface FreezeResult {
  ok: boolean;
  invoiceNo?: number;
  jsonPath?: string;
  pdfPath?: string;
  jsonSha?: string;
  pdfSha?: string;
  error?: string;
}

/**
 * Build the self-contained snapshot data object. Includes EVERYTHING needed to
 * re-render the PDF later with zero further DB reads.
 */
async function buildSnapshotData(invoiceId: string): Promise<Record<string, any> | null> {
  const invoice = await prisma.invoice.findUnique({
    where: { id: invoiceId },
    include: {
      customer: true,
      ethanolLiftings: {
        include: { contract: true },
      },
      ddgsContractDispatches: {
        include: {
          contract: true,
          ddgsDispatchTruck: true,
        },
      },
    },
  });

  if (!invoice) return null;

  const lifting = invoice.ethanolLiftings?.[0] || null;
  const ddgsLink = invoice.ddgsContractDispatches?.[0] || null;
  const ddgsTruck = ddgsLink?.ddgsDispatchTruck || null;
  const ddgsContract = ddgsLink?.contract || null;
  const isDDGSInvoice = !!ddgsLink || (invoice.productName || '').toUpperCase().includes('DDGS');

  const stateCode = invoice.customer.gstNo ? invoice.customer.gstNo.substring(0, 2) : '';
  const supplierCompany = await getCompanyForPdf(invoice.companyId);
  const customInvNo = lifting?.invoiceNo || invoice.remarks || null;

  // Shipment fallback for scrap/misc invoices
  const shipment = (!lifting && !ddgsLink && invoice.shipmentId)
    ? await prisma.shipment.findUnique({
        where: { id: invoice.shipmentId },
        select: {
          vehicleNo: true, driverName: true, driverMobile: true,
          transporterName: true, destination: true, customerName: true,
        },
      })
    : null;

  // HSN derivation (same logic as invoices.ts route for byte-equal rendering)
  const hsnCode = (() => {
    const p = (invoice.productName || '').toUpperCase();
    if (p.includes('JOBWORK') || p.includes('JOB WORK')) {
      if (p.includes('DDGS')) return '998817';
      if (p.includes('SUGAR')) return '998817';
      return '998842';
    }
    if (p.includes('ETHANOL')) return '22072000';
    if (p.includes('DDGS')) return '23033000';
    if (p.includes('SUGAR')) return '17019990';
    if (p.includes('PRESS MUD') || p.includes('PRESSMUD')) return '23031000';
    if (p.includes('SCRAP')) return '7204';
    if (p.includes('FLY ASH') || p.includes('ASH')) return '26219000';
    return '998817';
  })();

  const consignee = (() => {
    if (lifting?.consigneeName) {
      return {
        name: lifting.consigneeName,
        gstin: lifting.consigneeGstin || null,
        address: lifting.consigneeAddress || null,
        state: lifting.consigneeState || null,
        stateCode: lifting.consigneeGstin ? lifting.consigneeGstin.substring(0, 2) : null,
        pincode: lifting.consigneePincode || null,
      };
    }
    const inv = invoice as any;
    if (inv.shipToName) {
      return {
        name: inv.shipToName,
        gstin: inv.shipToGstin || null,
        address: inv.shipToAddress || null,
        state: inv.shipToState || null,
        stateCode: inv.shipToGstin ? inv.shipToGstin.substring(0, 2) : null,
        pincode: inv.shipToPincode || null,
      };
    }
    return null;
  })();

  return {
    schemaVersion: SCHEMA_VERSION,
    invoiceId: invoice.id,
    invoiceNo: invoice.invoiceNo,
    customInvoiceNo: customInvNo,
    invoiceDate: invoice.invoiceDate,
    dueDate: invoice.dueDate,
    challanNo: lifting?.challanNo || invoice.challanNo || ddgsLink?.challanNo || ddgsLink?.gatePassNo || null,
    ewayBill: invoice.ewayBill,
    paymentMode: lifting?.contract?.paymentTermsDays
      ? `${lifting.contract.paymentTermsDays} Days`
      : (lifting?.contract?.paymentMode
          || (ddgsContract?.paymentTermsDays ? `${ddgsContract.paymentTermsDays} Days` : null)
          || ddgsContract?.paymentMode
          || null),
    supplyType: invoice.supplyType,
    placeOfSupply: invoice.placeOfSupply,

    // Supplier snapshot (MSPIL or sister company)
    company: supplierCompany || null,

    // Buyer (Bill-To) snapshot
    customer: {
      id: invoice.customer.id,
      name: invoice.customer.name,
      shortName: invoice.customer.shortName,
      gstin: invoice.customer.gstNo,
      address: invoice.customer.address,
      city: invoice.customer.city,
      state: invoice.customer.state,
      stateCode,
      pincode: invoice.customer.pincode,
      phone: invoice.customer.phone,
      email: invoice.customer.email,
    },

    // Ship-To (consignee) snapshot
    consignee,

    // Line item (current schema: one line per invoice)
    productName: invoice.productName,
    hsnCode,
    // DDGS quantity + rate display conversion (MT → KG)
    quantity: isDDGSInvoice ? Math.round((invoice.quantity || 0) * 1000) : invoice.quantity,
    unit: isDDGSInvoice ? 'KG' : invoice.unit,
    rate: isDDGSInvoice ? Math.round(((invoice.rate || 0) / 1000) * 10000) / 10000 : invoice.rate,

    amount: invoice.amount,
    gstPercent: invoice.gstPercent,
    gstAmount: invoice.gstAmount,
    halfGst: invoice.gstAmount / 2,
    cgstAmount: invoice.cgstAmount || 0,
    sgstAmount: invoice.sgstAmount || 0,
    igstAmount: invoice.igstAmount || 0,
    cgstPercent: invoice.cgstPercent || 0,
    sgstPercent: invoice.sgstPercent || 0,
    igstPercent: invoice.igstPercent || 0,
    freightCharge: invoice.freightCharge,
    tcsPercent: (invoice as any).tcsPercent || 0,
    tcsAmount: (invoice as any).tcsAmount || 0,
    tcsSection: (invoice as any).tcsSection || null,
    totalAmount: invoice.totalAmount,
    roundedTotalAmount: Math.round(invoice.totalAmount || 0),
    roundOff: Math.round((Math.round(invoice.totalAmount || 0) - (invoice.totalAmount || 0)) * 100) / 100,

    remarks: invoice.remarks,

    // Transport
    vehicleNo: lifting?.vehicleNo || ddgsTruck?.vehicleNo || ddgsLink?.vehicleNo || shipment?.vehicleNo || null,
    driverName: lifting?.driverName || ddgsTruck?.driverName || ddgsLink?.driverName || shipment?.driverName || null,
    transporterName: lifting?.transporterName || ddgsTruck?.transporterName || ddgsLink?.transporterName || shipment?.transporterName || null,
    destination: lifting?.destination || ddgsTruck?.destination || ddgsLink?.destination || shipment?.destination || null,
    distanceKm: lifting?.distanceKm || ddgsLink?.distanceKm || null,
    strength: lifting?.strength || null,
    rstNo: lifting?.rstNo || (ddgsTruck?.rstNo ? String(ddgsTruck.rstNo) : null),
    dispatchMode: lifting?.dispatchMode || (isDDGSInvoice ? 'TRUCK' : 'TANKER'),
    productRatePerLtr: lifting?.productRatePerLtr || null,
    productValue: lifting?.productValue || null,

    // E-Invoice (frozen)
    irn: invoice.irn || null,
    irnDate: invoice.irnDate || null,
    irnStatus: invoice.irnStatus || null,
    ackNo: invoice.ackNo || null,
    signedQRCode: invoice.signedQRCode || null,

    // E-Way Bill (may not exist at snapshot time; re-snapshot on EWB generation is out of scope for Phase 1)
    ewbNo: invoice.ewbNo || null,
    ewbDate: invoice.ewbDate || null,
    ewbValidTill: invoice.ewbValidTill || null,

    // Source references (so we know what this invoice came from without DB lookup)
    references: {
      shipmentId: invoice.shipmentId,
      orderId: invoice.orderId,
      companyId: invoice.companyId,
      ethanolLiftingId: lifting?.id || null,
      ethanolContractNo: lifting?.contract?.contractNo || null,
      ddgsContractDispatchId: ddgsLink?.id || null,
      ddgsContractNo: ddgsContract?.contractNo || null,
      ddgsDispatchTruckId: ddgsTruck?.id || null,
    },

    frozenAt: new Date().toISOString(),
  };
}

/**
 * Freeze an invoice: write JSON + PDF snapshot to disk, store paths + SHA on Invoice row.
 * Safe to call multiple times; returns ok:false with error message if write fails.
 * Never throws — caller can .catch() defensively but doesn't have to.
 */
export async function freezeInvoice(invoiceId: string): Promise<FreezeResult> {
  try {
    const data = await buildSnapshotData(invoiceId);
    if (!data) return { ok: false, error: 'Invoice not found' };

    const invoiceNo = data.invoiceNo as number;
    const when = new Date();
    const yyyy = when.getFullYear();
    const mm = String(when.getMonth() + 1).padStart(2, '0');
    const subDir = path.join(String(yyyy), mm);
    const fileStem = `INV-${invoiceNo}`;

    // Paths stored on Invoice row are relative to SNAPSHOT_DIR (e.g. "2026/04/INV-248.json")
    // Absolute path = path.join(SNAPSHOT_DIR, relJsonPath)
    const relJsonPath = path.join(subDir, `${fileStem}.json`);
    const relPdfPath = path.join(subDir, `${fileStem}.pdf`);

    const absDir = path.join(SNAPSHOT_DIR, subDir);
    const absJsonPath = path.join(absDir, `${fileStem}.json`);
    const absPdfPath = path.join(absDir, `${fileStem}.pdf`);

    await fs.mkdir(absDir, { recursive: true });

    // Render PDF using the same pipeline as GET /:id/pdf
    const pdfBuffer = await renderDocumentPdf({
      docType: 'INVOICE',
      data,
      verifyId: invoiceId,
    });

    const jsonBuffer = Buffer.from(JSON.stringify(data, null, 2), 'utf-8');

    const jsonSha = createHash('sha256').update(jsonBuffer).digest('hex');
    const pdfSha = createHash('sha256').update(pdfBuffer).digest('hex');

    // Write both atomically-ish: JSON first, then PDF. If PDF write fails, JSON is a
    // harmless orphan — we can regenerate PDF from JSON later. Real atomic would need
    // a staging dir + rename, which we can add in Phase 2.
    await fs.writeFile(absJsonPath, jsonBuffer);
    await fs.writeFile(absPdfPath, pdfBuffer);

    await prisma.invoice.update({
      where: { id: invoiceId },
      data: {
        snapshotJsonPath: relJsonPath,
        snapshotPdfPath: relPdfPath,
        snapshotJsonSha: jsonSha,
        snapshotPdfSha: pdfSha,
        snapshotAt: when,
      } as any,
    });

    console.log(`[InvoiceSnapshot] Froze INV-${invoiceNo} → ${relJsonPath} (${jsonBuffer.length} B JSON, ${pdfBuffer.length} B PDF)`);

    return {
      ok: true,
      invoiceNo,
      jsonPath: relJsonPath,
      pdfPath: relPdfPath,
      jsonSha,
      pdfSha,
    };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`[InvoiceSnapshot] Freeze FAILED for invoice ${invoiceId}:`, msg);
    return { ok: false, error: msg };
  }
}

/**
 * Read-back helper for Phase 2 and audit scripts. Verifies SHA matches on-disk file.
 */
export async function loadSnapshotJson(invoiceId: string): Promise<Record<string, any> | null> {
  const invoice = await prisma.invoice.findUnique({
    where: { id: invoiceId },
    select: { snapshotJsonPath: true, snapshotJsonSha: true } as any,
  });
  const inv = invoice as any;
  if (!inv?.snapshotJsonPath) return null;

  const absPath = path.join(SNAPSHOT_DIR, inv.snapshotJsonPath);

  try {
    const buf = await fs.readFile(absPath);
    const sha = createHash('sha256').update(buf).digest('hex');
    if (sha !== inv.snapshotJsonSha) {
      console.error(`[InvoiceSnapshot] SHA MISMATCH on ${invoiceId}: file=${sha} db=${inv.snapshotJsonSha}`);
      return null;
    }
    return JSON.parse(buf.toString('utf-8'));
  } catch (err) {
    console.error(`[InvoiceSnapshot] Failed to load snapshot for ${invoiceId}:`, err);
    return null;
  }
}

export interface AuditRow {
  invoiceId: string;
  invoiceNo: number;
  status: 'ok' | 'json_sha_mismatch' | 'pdf_sha_mismatch' | 'json_missing' | 'pdf_missing' | 'read_error';
  detail?: string;
}

/**
 * Audit: walk every invoice with a snapshot, verify SHAs match disk.
 * Returns list of problems (ok rows omitted from detail unless includeOk=true).
 */
export async function auditAllSnapshots(limit = 500): Promise<{
  totalChecked: number;
  ok: number;
  issues: AuditRow[];
  checkedAt: string;
}> {
  const invoices = await prisma.invoice.findMany({
    where: { snapshotAt: { not: null } } as any,
    select: {
      id: true, invoiceNo: true,
      snapshotJsonPath: true, snapshotJsonSha: true,
      snapshotPdfPath: true, snapshotPdfSha: true,
    } as any,
    take: limit,
    orderBy: { invoiceNo: 'asc' },
  });

  const issues: AuditRow[] = [];
  let ok = 0;

  for (const inv of invoices as any[]) {
    const check = async (kind: 'json' | 'pdf', relPath: string, expectedSha: string): Promise<AuditRow['status'] | null> => {
      const absPath = path.join(SNAPSHOT_DIR, relPath);
      try {
        const buf = await fs.readFile(absPath);
        const sha = createHash('sha256').update(buf).digest('hex');
        if (sha !== expectedSha) return kind === 'json' ? 'json_sha_mismatch' : 'pdf_sha_mismatch';
        return null;
      } catch (err: any) {
        if (err?.code === 'ENOENT') return kind === 'json' ? 'json_missing' : 'pdf_missing';
        return 'read_error';
      }
    };

    const jsonStatus = await check('json', inv.snapshotJsonPath, inv.snapshotJsonSha);
    const pdfStatus = await check('pdf', inv.snapshotPdfPath, inv.snapshotPdfSha);

    if (jsonStatus) issues.push({ invoiceId: inv.id, invoiceNo: inv.invoiceNo, status: jsonStatus });
    if (pdfStatus) issues.push({ invoiceId: inv.id, invoiceNo: inv.invoiceNo, status: pdfStatus });
    if (!jsonStatus && !pdfStatus) ok++;
  }

  return {
    totalChecked: invoices.length,
    ok,
    issues,
    checkedAt: new Date().toISOString(),
  };
}
