import { Router, Response } from 'express';
import { authenticate, AuthRequest, getCompanyFilter, getActiveCompanyId, canAccessCompany } from '../middleware/auth';
import { asyncHandler, validate } from '../shared/middleware';
import { NotFoundError, ValidationError } from '../shared/errors';
import { z } from 'zod';
import prisma from '../config/prisma';
import { nextDocNo } from '../utils/docSequence';
import { DIVISIONS } from '../shared/config/divisions';

const router = Router();
router.use(authenticate as any);

// ── Types (for Prisma results) ──
interface JL { debit: number; credit: number }
interface AccountRow {
  id: string; code: string; name: string; type: string; subType: string | null;
  openingBalance: number; journalLines: JL[];
}
interface PLAccountRow {
  type: string; journalLines: JL[];
}

// ── Zod Schemas ──

const journalLineSchema = z.object({
  accountId: z.string().min(1),
  debit: z.number().min(0).default(0),
  credit: z.number().min(0).default(0),
  narration: z.string().optional().nullable(),
  costCenter: z.string().optional().nullable(),
  division: z.enum(DIVISIONS).optional().nullable(),
});

const createJournalSchema = z.object({
  date: z.string().min(1), // ISO date string
  narration: z.string().min(1),
  refType: z.enum(['SALE', 'PURCHASE', 'PAYMENT', 'RECEIPT', 'CONTRA', 'JOURNAL']).optional().nullable(),
  refId: z.string().optional().nullable(),
  lines: z.array(journalLineSchema).min(2), // at least 2 lines (double entry)
});

// ── GET / — List journal entries (paginated) ──
router.get('/', asyncHandler(async (req: AuthRequest, res: Response) => {
  const take = Math.min(parseInt(req.query.limit as string) || 50, 500);
  const skip = parseInt(req.query.offset as string) || 0;
  const fromStr = req.query.from as string | undefined;
  const toStr = req.query.to as string | undefined;
  const refType = req.query.refType as string | undefined;
  const divisionStr = req.query.division as string | undefined;

  const where: Record<string, unknown> = { ...getCompanyFilter(req) };
  if (fromStr || toStr) {
    where.date = {
      ...(fromStr ? { gte: new Date(fromStr) } : {}),
      ...(toStr ? { lte: new Date(toStr) } : {}),
    };
  }
  if (refType) where.refType = refType;
  if (divisionStr && (DIVISIONS as readonly string[]).includes(divisionStr)) {
    where.lines = { some: { division: divisionStr } };
  }

  const [entries, total] = await Promise.all([
    prisma.journalEntry.findMany({
      where,
      take,
      skip,
      orderBy: { date: 'desc' },
      select: {
        id: true,
        entryNo: true,
        date: true,
        narration: true,
        refType: true,
        refId: true,
        isAutoGenerated: true,
        isReversed: true,
        userId: true,
        createdAt: true,
        lines: {
          select: {
            id: true,
            accountId: true,
            account: { select: { code: true, name: true, type: true } },
            debit: true,
            credit: true,
            narration: true,
            costCenter: true,
            division: true,
          },
        },
      },
    }),
    prisma.journalEntry.count({ where }),
  ]);

  res.json({ entries, total, take, skip });
}));

// ── GET /daybook — Entries for a day OR a range, optional division filter ──
// Back-compat: `?date=YYYY-MM-DD` still works (single day).
// New: `?from=YYYY-MM-DD&to=YYYY-MM-DD&division=SUGAR|POWER|ETHANOL|COMMON`.
router.get('/daybook', asyncHandler(async (req: AuthRequest, res: Response) => {
  const dateStr = req.query.date as string | undefined;
  const fromStr = req.query.from as string | undefined;
  const toStr = req.query.to as string | undefined;
  const divisionStr = req.query.division as string | undefined;

  let rangeStart: Date;
  let rangeEnd: Date;

  if (dateStr) {
    rangeStart = new Date(dateStr);
    rangeStart.setHours(0, 0, 0, 0);
    rangeEnd = new Date(dateStr);
    rangeEnd.setHours(23, 59, 59, 999);
  } else if (fromStr && toStr) {
    rangeStart = new Date(fromStr);
    rangeStart.setHours(0, 0, 0, 0);
    rangeEnd = new Date(toStr);
    rangeEnd.setHours(23, 59, 59, 999);
  } else {
    res.status(400).json({ error: 'Provide either ?date=YYYY-MM-DD or ?from=&to=' });
    return;
  }

  const where: Record<string, unknown> = { date: { gte: rangeStart, lte: rangeEnd }, ...getCompanyFilter(req) };
  if (divisionStr && (DIVISIONS as readonly string[]).includes(divisionStr)) {
    where.lines = { some: { division: divisionStr } };
  }

  const entries = await prisma.journalEntry.findMany({
    where,
    orderBy: [{ date: 'asc' }, { entryNo: 'asc' }],
    take: 500,
    select: {
      id: true,
      entryNo: true,
      date: true,
      narration: true,
      refType: true,
      isAutoGenerated: true,
      isReversed: true,
      lines: {
        select: {
          account: { select: { code: true, name: true } },
          debit: true,
          credit: true,
          costCenter: true,
          division: true,
        },
      },
    },
  });

  const totalDebit = entries.reduce((s: number, e: { lines: JL[] }) => s + e.lines.reduce((ls: number, l: JL) => ls + l.debit, 0), 0);
  const totalCredit = entries.reduce((s: number, e: { lines: JL[] }) => s + e.lines.reduce((ls: number, l: JL) => ls + l.credit, 0), 0);

  res.json({
    date: dateStr || null,
    from: fromStr || null,
    to: toStr || null,
    entries,
    count: entries.length,
    totalDebit,
    totalCredit,
  });
}));

// ── GET /ledger/:accountId — Ledger for a specific account ──
router.get('/ledger/:accountId', asyncHandler(async (req: AuthRequest, res: Response) => {
  const { accountId } = req.params;
  const fromStr = req.query.from as string | undefined;
  const toStr = req.query.to as string | undefined;
  const divisionStr = req.query.division as string | undefined;
  const take = Math.min(parseInt(req.query.limit as string) || 200, 500);

  const account = await prisma.account.findUnique({
    where: { id: accountId },
    select: { id: true, code: true, name: true, type: true, openingBalance: true },
  });
  if (!account) throw new NotFoundError('Account', accountId);

  const where: Record<string, unknown> = {
    accountId,
    journal: { isReversed: false },
  };

  if (fromStr || toStr) {
    (where.journal as Record<string, unknown>).date = {
      ...(fromStr ? { gte: new Date(fromStr) } : {}),
      ...(toStr ? { lte: new Date(toStr) } : {}),
    };
  }
  if (divisionStr && (DIVISIONS as readonly string[]).includes(divisionStr)) {
    where.division = divisionStr;
  }

  const lines = await prisma.journalLine.findMany({
    where,
    take,
    orderBy: { journal: { date: 'asc' } },
    select: {
      id: true,
      debit: true,
      credit: true,
      narration: true,
      costCenter: true,
      division: true,
      journal: {
        select: {
          id: true,
          entryNo: true,
          date: true,
          narration: true,
          refType: true,
          refId: true,
        },
      },
    },
  });

  // Resolve party name (customer/vendor) per journal entry from refType + refId.
  // Batch-fetch once per ref type to keep this O(1) lookups.
  const partyByRef = new Map<string, string>();
  const collect = (type: string) => [...new Set(
    lines.filter(l => l.journal.refType === type && l.journal.refId).map(l => l.journal.refId as string)
  )];

  const saleIds = collect('SALE');
  const payIds = collect('PAYMENT');
  const recvIds = collect('RECEIPT');
  const purchIds = collect('PURCHASE');

  const [sales, vendorPays, recvs, vendorInvs, stockMoves] = await Promise.all([
    saleIds.length ? prisma.invoice.findMany({ where: { id: { in: saleIds } }, select: { id: true, customer: { select: { name: true } } } ,
    take: 500,
  }) : [],
    payIds.length ? prisma.vendorPayment.findMany({ where: { id: { in: payIds } }, select: { id: true, vendor: { select: { name: true } } } ,
    take: 500,
  }) : [],
    recvIds.length ? prisma.payment.findMany({ where: { id: { in: recvIds } }, select: { id: true, invoice: { select: { customer: { select: { name: true } } } } } ,
    take: 500,
  }).catch(() => []) : [],
    purchIds.length ? prisma.vendorInvoice.findMany({ where: { id: { in: purchIds } }, select: { id: true, vendor: { select: { name: true } } } ,
    take: 500,
  }) : [],
    purchIds.length ? prisma.stockMovement.findMany({
      where: { id: { in: purchIds } },
      select: { id: true, refId: true, refType: true },
    
    take: 500,
  }) : [],
  ]);
  for (const s of sales)       if (s.customer?.name) partyByRef.set(`SALE:${s.id}`, s.customer.name);
  for (const v of vendorPays)  if (v.vendor?.name)   partyByRef.set(`PAYMENT:${v.id}`, v.vendor.name);
  for (const r of recvs)       if (r.invoice?.customer?.name) partyByRef.set(`RECEIPT:${r.id}`, r.invoice.customer.name);
  for (const vi of vendorInvs) if (vi.vendor?.name)  partyByRef.set(`PURCHASE:${vi.id}`, vi.vendor.name);
  // StockMovement (GRN_RECEIPT) → follow refId to GoodsReceipt → po.vendor
  const grnIds = stockMoves.filter(m => m.refType === 'GRN').map(m => m.refId).filter(Boolean) as string[];
  if (grnIds.length) {
    const grns = await prisma.goodsReceipt.findMany({
      where: { id: { in: grnIds } },
      select: { id: true, po: { select: { vendor: { select: { name: true } } } } },
    
    take: 500,
  });
    const grnVendor = new Map(grns.map(g => [g.id, g.po?.vendor?.name || null]));
    for (const sm of stockMoves) {
      const v = sm.refId ? grnVendor.get(sm.refId) : null;
      if (v) partyByRef.set(`PURCHASE:${sm.id}`, v);
    }
  }

  // Calculate running balance
  const isDebitNormal = account.type === 'ASSET' || account.type === 'EXPENSE';
  let runningBalance = account.openingBalance;

  const ledgerLines = lines.map((l: { debit: number; credit: number; id: string; narration: string | null; costCenter: string | null; division: string | null; journal: { id: string; entryNo: number; date: Date; narration: string; refType: string | null; refId: string | null } }) => {
    if (isDebitNormal) {
      runningBalance += l.debit - l.credit;
    } else {
      runningBalance += l.credit - l.debit;
    }
    const party = l.journal.refType && l.journal.refId ? partyByRef.get(`${l.journal.refType}:${l.journal.refId}`) ?? null : null;
    return {
      ...l,
      party,
      balance: Math.round(runningBalance * 100) / 100,
    };
  });

  const totalDebit = lines.reduce((s: number, l: JL) => s + l.debit, 0);
  const totalCredit = lines.reduce((s: number, l: JL) => s + l.credit, 0);

  res.json({
    account,
    openingBalance: account.openingBalance,
    closingBalance: Math.round(runningBalance * 100) / 100,
    totalDebit,
    totalCredit,
    lines: ledgerLines,
  });
}));

// ── GET /trial-balance — Trial balance for a period ──
router.get('/trial-balance', asyncHandler(async (req: AuthRequest, res: Response) => {
  const fromStr = req.query.from as string | undefined;
  const toStr = req.query.to as string | undefined;

  const accounts = await prisma.account.findMany({
    where: { isActive: true, ...getCompanyFilter(req) },
    orderBy: { code: 'asc' },
    take: 500,
    select: {
      id: true,
      code: true,
      name: true,
      type: true,
      openingBalance: true,
      journalLines: {
        where: {
          journal: {
            isReversed: false,
            ...(fromStr || toStr ? {
              date: {
                ...(fromStr ? { gte: new Date(fromStr) } : {}),
                ...(toStr ? { lte: new Date(toStr) } : {}),
              },
            } : {}),
          },
        },
        select: { debit: true, credit: true },
      },
    },
  });

  let totalDebit = 0;
  let totalCredit = 0;

  const rows = (accounts as AccountRow[]).map((a: AccountRow) => {
    const debit = a.journalLines.reduce((s: number, l: JL) => s + l.debit, 0);
    const credit = a.journalLines.reduce((s: number, l: JL) => s + l.credit, 0);
    const isDebitNormal = a.type === 'ASSET' || a.type === 'EXPENSE';
    const closing = isDebitNormal
      ? a.openingBalance + debit - credit
      : a.openingBalance + credit - debit;

    // In trial balance, show debit or credit column based on sign
    const tbDebit = closing > 0 && isDebitNormal ? closing : (!isDebitNormal && closing < 0 ? Math.abs(closing) : 0);
    const tbCredit = closing > 0 && !isDebitNormal ? closing : (isDebitNormal && closing < 0 ? Math.abs(closing) : 0);

    // Simpler: if closing is positive for debit-normal → debit column, else credit column
    const finalDebit = isDebitNormal ? (closing >= 0 ? closing : 0) : (closing < 0 ? Math.abs(closing) : 0);
    const finalCredit = !isDebitNormal ? (closing >= 0 ? closing : 0) : (closing < 0 ? Math.abs(closing) : 0);

    totalDebit += finalDebit;
    totalCredit += finalCredit;

    return {
      id: a.id,
      code: a.code,
      name: a.name,
      type: a.type,
      openingBalance: a.openingBalance,
      periodDebit: debit,
      periodCredit: credit,
      closingBalance: Math.round(closing * 100) / 100,
      debit: Math.round(finalDebit * 100) / 100,
      credit: Math.round(finalCredit * 100) / 100,
    };
  }).filter(r => r.debit !== 0 || r.credit !== 0 || r.openingBalance !== 0);

  res.json({
    rows,
    totalDebit: Math.round(totalDebit * 100) / 100,
    totalCredit: Math.round(totalCredit * 100) / 100,
    isBalanced: Math.abs(totalDebit - totalCredit) < 0.01,
  });
}));

// ── GET /profit-loss — Income Statement ──
router.get('/profit-loss', asyncHandler(async (req: AuthRequest, res: Response) => {
  const fromStr = req.query.from as string | undefined;
  const toStr = req.query.to as string | undefined;

  const dateFilter = fromStr || toStr ? {
    date: {
      ...(fromStr ? { gte: new Date(fromStr) } : {}),
      ...(toStr ? { lte: new Date(toStr) } : {}),
    },
  } : {};

  const accounts = await prisma.account.findMany({
    where: { isActive: true, type: { in: ['INCOME', 'EXPENSE'] }, ...getCompanyFilter(req) },
    orderBy: { code: 'asc' },
    take: 500,
    select: {
      id: true, code: true, name: true, type: true, subType: true,
      journalLines: {
        where: { journal: { isReversed: false, ...dateFilter } },
        select: { debit: true, credit: true },
      },
    },
  });

  type PLRow = { id: string; code: string; name: string; type: string; subType: string | null; journalLines: JL[] };
  const incomeAccounts = (accounts as PLRow[]).filter((a: PLRow) => a.type === 'INCOME').map((a: PLRow) => {
    const amount = a.journalLines.reduce((s: number, l: JL) => s + l.credit - l.debit, 0);
    return { id: a.id, code: a.code, name: a.name, subType: a.subType, amount: Math.round(amount * 100) / 100 };
  }).filter((a: { amount: number }) => a.amount !== 0);

  const expenseAccounts = (accounts as PLRow[]).filter((a: PLRow) => a.type === 'EXPENSE').map((a: PLRow) => {
    const amount = a.journalLines.reduce((s: number, l: JL) => s + l.debit - l.credit, 0);
    return { id: a.id, code: a.code, name: a.name, subType: a.subType, amount: Math.round(amount * 100) / 100 };
  }).filter((a: { amount: number }) => a.amount !== 0);

  const totalIncome = incomeAccounts.reduce((s: number, a: { amount: number }) => s + a.amount, 0);
  const totalExpense = expenseAccounts.reduce((s: number, a: { amount: number }) => s + a.amount, 0);
  const netProfitLoss = Math.round((totalIncome - totalExpense) * 100) / 100;

  res.json({
    income: incomeAccounts,
    expenses: expenseAccounts,
    totalIncome: Math.round(totalIncome * 100) / 100,
    totalExpense: Math.round(totalExpense * 100) / 100,
    netProfitLoss,
    isProfit: netProfitLoss >= 0,
  });
}));

// ── GET /balance-sheet — Balance Sheet ──
router.get('/balance-sheet', asyncHandler(async (req: AuthRequest, res: Response) => {
  const toStr = req.query.asOn as string | undefined;
  const asOnDate = toStr ? new Date(toStr) : new Date();

  const accounts = await prisma.account.findMany({
    where: { isActive: true, type: { in: ['ASSET', 'LIABILITY', 'EQUITY'] }, ...getCompanyFilter(req) },
    orderBy: { code: 'asc' },
    take: 500,
    select: {
      id: true, code: true, name: true, type: true, subType: true, openingBalance: true,
      journalLines: {
        where: { journal: { isReversed: false, date: { lte: asOnDate } } },
        select: { debit: true, credit: true },
      },
    },
  });

  // Also calculate P&L for retained earnings
  const plAccounts = await prisma.account.findMany({
    where: { isActive: true, type: { in: ['INCOME', 'EXPENSE'] }, ...getCompanyFilter(req) },
    take: 500,
    select: {
      type: true,
      journalLines: {
        where: { journal: { isReversed: false, date: { lte: asOnDate } } },
        select: { debit: true, credit: true },
      },
    },
  });

  const totalIncome = (plAccounts as PLAccountRow[]).filter((a: PLAccountRow) => a.type === 'INCOME')
    .reduce((s: number, a: PLAccountRow) => s + a.journalLines.reduce((ls: number, l: JL) => ls + l.credit - l.debit, 0), 0);
  const totalExpense = (plAccounts as PLAccountRow[]).filter((a: PLAccountRow) => a.type === 'EXPENSE')
    .reduce((s: number, a: PLAccountRow) => s + a.journalLines.reduce((ls: number, l: JL) => ls + l.debit - l.credit, 0), 0);
  const retainedPL = totalIncome - totalExpense;

  const buildSection = (type: string): { accounts: { id: string; code: string; name: string; subType: string | null; balance: number }[]; total: number } => {
    const isDebitNormal = type === 'ASSET';
    const accs = (accounts as AccountRow[]).filter((a: AccountRow) => a.type === type).map((a: AccountRow) => {
      const tDebit = a.journalLines.reduce((s: number, l: JL) => s + l.debit, 0);
      const tCredit = a.journalLines.reduce((s: number, l: JL) => s + l.credit, 0);
      const balance = isDebitNormal
        ? a.openingBalance + tDebit - tCredit
        : a.openingBalance + tCredit - tDebit;
      return { id: a.id, code: a.code, name: a.name, subType: a.subType, balance: Math.round(balance * 100) / 100 };
    }).filter((a: { balance: number }) => a.balance !== 0);

    return { accounts: accs, total: accs.reduce((s: number, a: { balance: number }) => s + a.balance, 0) };
  };

  const assets = buildSection('ASSET');
  const liabilities = buildSection('LIABILITY');
  const equity = buildSection('EQUITY');

  // Equity total includes retained P&L
  const equityTotal = Math.round((equity.total + retainedPL) * 100) / 100;
  const liabilitiesAndEquity = Math.round((liabilities.total + equityTotal) * 100) / 100;

  res.json({
    asOnDate: asOnDate.toISOString().split('T')[0],
    assets: { accounts: assets.accounts, total: Math.round(assets.total * 100) / 100 },
    liabilities: { accounts: liabilities.accounts, total: Math.round(liabilities.total * 100) / 100 },
    equity: {
      accounts: [...equity.accounts, { id: 'retained-pl', code: '—', name: 'Current Year P&L', subType: null, balance: Math.round(retainedPL * 100) / 100 }],
      total: equityTotal,
    },
    liabilitiesAndEquity,
    isBalanced: Math.abs(assets.total - liabilitiesAndEquity) < 0.01,
  });
}));

// ── GET /:id — Single journal entry detail ──
router.get('/:id', asyncHandler(async (req: AuthRequest, res: Response) => {
  const entry = await prisma.journalEntry.findUnique({
    where: { id: req.params.id },
    include: {
      lines: {
        include: {
          account: { select: { code: true, name: true, type: true } },
        },
      },
    },
  });
  if (!entry) throw new NotFoundError('Journal Entry', req.params.id);
  if (!canAccessCompany(req, entry.companyId)) throw new NotFoundError('Journal Entry', req.params.id);
  res.json(entry);
}));

// ── POST / — Create manual journal entry ──
router.post('/', validate(createJournalSchema), asyncHandler(async (req: AuthRequest, res: Response) => {
  const { date, narration, refType, refId, lines } = req.body;

  // Validate: total debits must equal total credits
  const totalDebit = lines.reduce((s: number, l: { debit: number }) => s + l.debit, 0);
  const totalCredit = lines.reduce((s: number, l: { credit: number }) => s + l.credit, 0);

  if (Math.abs(totalDebit - totalCredit) > 0.01) {
    throw new ValidationError(
      `Debits (₹${totalDebit.toFixed(2)}) must equal Credits (₹${totalCredit.toFixed(2)}). Difference: ₹${Math.abs(totalDebit - totalCredit).toFixed(2)}`
    );
  }

  // Validate: each line must have either debit OR credit (not both)
  for (const line of lines) {
    if (line.debit > 0 && line.credit > 0) {
      throw new ValidationError('Each journal line must have either debit or credit, not both');
    }
    if (line.debit === 0 && line.credit === 0) {
      throw new ValidationError('Each journal line must have a non-zero debit or credit');
    }
  }

  // Validate all account IDs exist
  const accountIds = [...new Set(lines.map((l: { accountId: string }) => l.accountId))];
  const accounts = await prisma.account.findMany({
    where: { id: { in: accountIds as string[] } },
    select: { id: true },
  
    take: 500,
  });
  if (accounts.length !== accountIds.length) {
    throw new ValidationError('One or more account IDs are invalid');
  }

  const companyId = getActiveCompanyId(req);
  const entryNo = await nextDocNo('JournalEntry', 'entryNo', companyId);

  const entry = await prisma.$transaction(async (tx) => {
    const journal = await tx.journalEntry.create({
      data: {
        entryNo,
        date: new Date(date),
        narration,
        refType: refType || 'JOURNAL',
        refId: refId || null,
        userId: req.user?.id || 'system',
        companyId,
        lines: {
          create: lines.map((l: { accountId: string; debit: number; credit: number; narration?: string; costCenter?: string; division?: string }) => ({
            accountId: l.accountId,
            debit: l.debit,
            credit: l.credit,
            narration: l.narration || null,
            costCenter: l.costCenter || null,
            division: l.division || null,
          })),
        },
      },
      include: {
        lines: {
          include: {
            account: { select: { code: true, name: true } },
          },
        },
      },
    });
    return journal;
  });

  res.status(201).json(entry);
}));

// ── POST /:id/reverse — Reverse a journal entry (create opposite entry) ──
router.post('/:id/reverse', asyncHandler(async (req: AuthRequest, res: Response) => {
  const original = await prisma.journalEntry.findUnique({
    where: { id: req.params.id },
    include: { lines: true },
  });
  if (!original) throw new NotFoundError('Journal Entry', req.params.id);
  if (!canAccessCompany(req, original.companyId)) throw new NotFoundError('Journal Entry', req.params.id);

  if (original.isReversed) {
    throw new ValidationError('This entry has already been reversed');
  }

  const reversal = await prisma.$transaction(async (tx) => {
    // Mark original as reversed
    await tx.journalEntry.update({
      where: { id: original.id },
      data: { isReversed: true },
    });

    // Create reversal entry (swap debits and credits)
    const rev = await tx.journalEntry.create({
      data: {
        date: new Date(),
        narration: `Reversal of Entry #${original.entryNo}: ${original.narration}`,
        refType: original.refType,
        refId: original.refId,
        isAutoGenerated: false,
        reversalOf: original.id,
        userId: req.user?.id || 'system',
        companyId: original.companyId,
        lines: {
          create: original.lines.map((l: { accountId: string; debit: number; credit: number; costCenter: string | null }) => ({
            accountId: l.accountId,
            debit: l.credit,   // swap
            credit: l.debit,   // swap
            narration: `Reversal`,
            costCenter: l.costCenter,
          })),
        },
      },
      include: {
        lines: {
          include: { account: { select: { code: true, name: true } } },
        },
      },
    });
    return rev;
  });

  res.status(201).json({ message: 'Entry reversed', original: original.id, reversal });
}));

export default router;
