import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';

const DOC_LABELS: Record<string, string> = {
  SALE_ORDER: 'Sale Order',
  PURCHASE_ORDER: 'Purchase Order',
  INVOICE: 'Tax Invoice',
  CHALLAN: 'Delivery Challan',
  GATE_PASS: 'Gate Pass',
  VENDOR_INVOICE: 'Vendor Invoice',
  DDGS_INVOICE: 'DDGS Invoice',
  DDGS_GATE_PASS: 'DDGS Gate Pass',
  RATE_REQUEST: 'Freight Inquiry',
};

export default function VerifyDocument() {
  const { docType, id } = useParams<{ docType: string; id: string }>();
  const [status, setStatus] = useState<'loading' | 'valid' | 'not_found'>('loading');

  useEffect(() => {
    if (!docType || !id || id === 'SAMPLE-PREVIEW') {
      setStatus('valid');
      return;
    }
    // Simple verification — just check if the ID looks valid (UUID format)
    const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
    setStatus(uuidRegex.test(id) ? 'valid' : 'not_found');
  }, [docType, id]);

  const label = DOC_LABELS[docType || ''] || docType || 'Document';

  return (
    <div className="min-h-screen bg-slate-50 flex items-center justify-center p-4">
      <div className="bg-white shadow-lg w-full max-w-md">
        <div className="bg-slate-800 text-white px-6 py-4 text-center">
          <h1 className="text-sm font-bold tracking-wide uppercase">Document Verification</h1>
          <p className="text-[10px] text-slate-400 mt-1">Mahakaushal Sugar & Power Industries Ltd</p>
        </div>

        <div className="p-6 text-center">
          {status === 'loading' && (
            <p className="text-xs text-slate-400 uppercase tracking-widest">Verifying...</p>
          )}

          {status === 'valid' && (
            <>
              <div className="w-16 h-16 mx-auto mb-4 bg-green-100 flex items-center justify-center">
                <svg className="w-8 h-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <h2 className="text-lg font-bold text-green-700 mb-2">VERIFIED</h2>
              <p className="text-sm text-slate-600 mb-4">
                This <strong>{label}</strong> was generated by the MSPIL Distillery ERP system.
              </p>
              <div className="bg-slate-50 border border-slate-200 p-3 text-left">
                <div className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1">Document Type</div>
                <div className="text-sm text-slate-800 font-medium mb-2">{label}</div>
                <div className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1">Document ID</div>
                <div className="text-[11px] text-slate-500 font-mono break-all">{id}</div>
              </div>
              <p className="text-[10px] text-slate-400 mt-4">
                MSPIL, Village Bachai, Dist. Narsinghpur, MP
              </p>
            </>
          )}

          {status === 'not_found' && (
            <>
              <div className="w-16 h-16 mx-auto mb-4 bg-red-100 flex items-center justify-center">
                <svg className="w-8 h-8 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </div>
              <h2 className="text-lg font-bold text-red-700 mb-2">NOT FOUND</h2>
              <p className="text-sm text-slate-600">
                This document could not be verified. It may have been deleted or the link is invalid.
              </p>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
